// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The error type indicates whether a connection error is consumer facing,
/// producer facing or system internal.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum ConnectionErrorType: Codable, Equatable, Hashable, Sendable {
  /// An invalid error type as the default case.
  case unspecified
  /// The error is due to Service Automation system internal.
  case errorInternal
  /// The error is due to the setup on consumer side.
  case errorConsumerSide
  /// The error is due to the setup on producer side.
  case errorProducerSide
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .errorInternal: return 1
    case .errorConsumerSide: return 2
    case .errorProducerSide: return 3
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "CONNECTION_ERROR_TYPE_UNSPECIFIED"
    case .errorInternal: return "ERROR_INTERNAL"
    case .errorConsumerSide: return "ERROR_CONSUMER_SIDE"
    case .errorProducerSide: return "ERROR_PRODUCER_SIDE"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ConnectionErrorType/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "CONNECTION_ERROR_TYPE_UNSPECIFIED": self = .unspecified
    case "ERROR_INTERNAL": self = .errorInternal
    case "ERROR_CONSUMER_SIDE": self = .errorConsumerSide
    case "ERROR_PRODUCER_SIDE": self = .errorProducerSide
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ConnectionErrorType/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .errorInternal
    case 2: self = .errorConsumerSide
    case 3: self = .errorProducerSide
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("CONNECTION_ERROR_TYPE_UNSPECIFIED")
    case .errorInternal: return try container.encode("ERROR_INTERNAL")
    case .errorConsumerSide: return try container.encode("ERROR_CONSUMER_SIDE")
    case .errorProducerSide: return try container.encode("ERROR_PRODUCER_SIDE")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
