// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleIAMV1
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// The service for CrossNetworkAutomation resources.
///
/// @Snippet(path: "CrossNetworkAutomationServiceQuickstart")
public final class CrossNetworkAutomationServiceClient: Clients
    .CrossNetworkAutomationServiceProtocol, Sendable
{
  let inner: any Clients.CrossNetworkAutomationServiceStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.PollingBackoffPolicy

  /// Creates a new `CrossNetworkAutomationServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.CrossNetworkAutomationServiceStub =
      try Clients.CrossNetworkAutomationServiceTransport(options)
    inner = Clients.CrossNetworkAutomationServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.CrossNetworkAutomationServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists ServiceConnectionMaps in a given project and location.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_ListServiceConnectionMaps")
  public func listServiceConnectionMaps(
    request: ListServiceConnectionMapsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionMapsResponse {
    try await self.inner.listServiceConnectionMaps(request: request, options: options)
  }

  /// Gets details of a single ServiceConnectionMap.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_GetServiceConnectionMap")
  public func getServiceConnectionMap(
    request: GetServiceConnectionMapRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceConnectionMap {
    try await self.inner.getServiceConnectionMap(request: request, options: options)
  }

  /// Creates a new ServiceConnectionMap in a given project and location.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_CreateServiceConnectionMap")
  public func createServiceConnectionMap(
    request: CreateServiceConnectionMapRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createServiceConnectionMap(request: request, options: options)
  }

  /// Creates a new ServiceConnectionMap in a given project and location.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_CreateServiceConnectionMap")
  public func createServiceConnectionMapPollingUntilDone(
    request: CreateServiceConnectionMapRequest, options: GoogleGax.RequestOptions
  ) async throws -> ServiceConnectionMap {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ServiceConnectionMap>.State in
      return try op._extractStatus(ServiceConnectionMap.self)
    }
    let rawOp = try await self.createServiceConnectionMap(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<ServiceConnectionMap>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Updates the parameters of a single ServiceConnectionMap.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_UpdateServiceConnectionMap")
  public func updateServiceConnectionMap(
    request: UpdateServiceConnectionMapRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateServiceConnectionMap(request: request, options: options)
  }

  /// Updates the parameters of a single ServiceConnectionMap.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_UpdateServiceConnectionMap")
  public func updateServiceConnectionMapPollingUntilDone(
    request: UpdateServiceConnectionMapRequest, options: GoogleGax.RequestOptions
  ) async throws -> ServiceConnectionMap {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ServiceConnectionMap>.State in
      return try op._extractStatus(ServiceConnectionMap.self)
    }
    let rawOp = try await self.updateServiceConnectionMap(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<ServiceConnectionMap>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Deletes a single ServiceConnectionMap.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_DeleteServiceConnectionMap")
  public func deleteServiceConnectionMap(
    request: DeleteServiceConnectionMapRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteServiceConnectionMap(request: request, options: options)
  }

  /// Deletes a single ServiceConnectionMap.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_DeleteServiceConnectionMap")
  public func deleteServiceConnectionMapPollingUntilDone(
    request: DeleteServiceConnectionMapRequest, options: GoogleGax.RequestOptions
  ) async throws {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteServiceConnectionMap(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    try await poller.wait()
  }

  /// Lists ServiceConnectionPolicies in a given project and location.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_ListServiceConnectionPolicies")
  public func listServiceConnectionPolicies(
    request: ListServiceConnectionPoliciesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionPoliciesResponse {
    try await self.inner.listServiceConnectionPolicies(request: request, options: options)
  }

  /// Gets details of a single ServiceConnectionPolicy.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_GetServiceConnectionPolicy")
  public func getServiceConnectionPolicy(
    request: GetServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceConnectionPolicy {
    try await self.inner.getServiceConnectionPolicy(request: request, options: options)
  }

  /// Creates a new ServiceConnectionPolicy in a given project and location.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_CreateServiceConnectionPolicy")
  public func createServiceConnectionPolicy(
    request: CreateServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createServiceConnectionPolicy(request: request, options: options)
  }

  /// Creates a new ServiceConnectionPolicy in a given project and location.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_CreateServiceConnectionPolicy")
  public func createServiceConnectionPolicyPollingUntilDone(
    request: CreateServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> ServiceConnectionPolicy {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ServiceConnectionPolicy>.State in
      return try op._extractStatus(ServiceConnectionPolicy.self)
    }
    let rawOp = try await self.createServiceConnectionPolicy(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<ServiceConnectionPolicy>.State
      in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Updates the parameters of a single ServiceConnectionPolicy.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_UpdateServiceConnectionPolicy")
  public func updateServiceConnectionPolicy(
    request: UpdateServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateServiceConnectionPolicy(request: request, options: options)
  }

  /// Updates the parameters of a single ServiceConnectionPolicy.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_UpdateServiceConnectionPolicy")
  public func updateServiceConnectionPolicyPollingUntilDone(
    request: UpdateServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> ServiceConnectionPolicy {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ServiceConnectionPolicy>.State in
      return try op._extractStatus(ServiceConnectionPolicy.self)
    }
    let rawOp = try await self.updateServiceConnectionPolicy(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<ServiceConnectionPolicy>.State
      in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Deletes a single ServiceConnectionPolicy.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_DeleteServiceConnectionPolicy")
  public func deleteServiceConnectionPolicy(
    request: DeleteServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteServiceConnectionPolicy(request: request, options: options)
  }

  /// Deletes a single ServiceConnectionPolicy.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_DeleteServiceConnectionPolicy")
  public func deleteServiceConnectionPolicyPollingUntilDone(
    request: DeleteServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteServiceConnectionPolicy(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    try await poller.wait()
  }

  /// Lists ServiceClasses in a given project and location.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_ListServiceClasses")
  public func listServiceClasses(
    request: ListServiceClassesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceClassesResponse {
    try await self.inner.listServiceClasses(request: request, options: options)
  }

  /// Gets details of a single ServiceClass.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_GetServiceClass")
  public func getServiceClass(
    request: GetServiceClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceClass {
    try await self.inner.getServiceClass(request: request, options: options)
  }

  /// Updates the parameters of a single ServiceClass.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_UpdateServiceClass")
  public func updateServiceClass(
    request: UpdateServiceClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateServiceClass(request: request, options: options)
  }

  /// Updates the parameters of a single ServiceClass.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_UpdateServiceClass")
  public func updateServiceClassPollingUntilDone(
    request: UpdateServiceClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> ServiceClass {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ServiceClass>.State in
      return try op._extractStatus(ServiceClass.self)
    }
    let rawOp = try await self.updateServiceClass(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<ServiceClass>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Deletes a single ServiceClass.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_DeleteServiceClass")
  public func deleteServiceClass(
    request: DeleteServiceClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteServiceClass(request: request, options: options)
  }

  /// Deletes a single ServiceClass.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_DeleteServiceClass")
  public func deleteServiceClassPollingUntilDone(
    request: DeleteServiceClassRequest, options: GoogleGax.RequestOptions
  ) async throws {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteServiceClass(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    try await poller.wait()
  }

  /// Gets details of a single ServiceConnectionToken.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_GetServiceConnectionToken")
  public func getServiceConnectionToken(
    request: GetServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceConnectionToken {
    try await self.inner.getServiceConnectionToken(request: request, options: options)
  }

  /// Lists ServiceConnectionTokens in a given project and location.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_ListServiceConnectionTokens")
  public func listServiceConnectionTokens(
    request: ListServiceConnectionTokensRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionTokensResponse {
    try await self.inner.listServiceConnectionTokens(request: request, options: options)
  }

  /// Creates a new ServiceConnectionToken in a given project and location.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_CreateServiceConnectionToken")
  public func createServiceConnectionToken(
    request: CreateServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createServiceConnectionToken(request: request, options: options)
  }

  /// Creates a new ServiceConnectionToken in a given project and location.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_CreateServiceConnectionToken")
  public func createServiceConnectionTokenPollingUntilDone(
    request: CreateServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> ServiceConnectionToken {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ServiceConnectionToken>.State in
      return try op._extractStatus(ServiceConnectionToken.self)
    }
    let rawOp = try await self.createServiceConnectionToken(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<ServiceConnectionToken>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Deletes a single ServiceConnectionToken.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_DeleteServiceConnectionToken")
  public func deleteServiceConnectionToken(
    request: DeleteServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteServiceConnectionToken(request: request, options: options)
  }

  /// Deletes a single ServiceConnectionToken.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_DeleteServiceConnectionToken")
  public func deleteServiceConnectionTokenPollingUntilDone(
    request: DeleteServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
  ) async throws {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteServiceConnectionToken(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    try await poller.wait()
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `CrossNetworkAutomationServiceClient`.
  ///
  /// To mock `CrossNetworkAutomationServiceClient` change your functions to receive
  /// `some CrossNetworkAutomationServiceProtocol` or `any CrossNetworkAutomationServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol CrossNetworkAutomationServiceProtocol: Sendable {
    /// See `CrossNetworkAutomationServiceClient.listServiceConnectionMaps`.
    func listServiceConnectionMaps(
      request: ListServiceConnectionMapsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionMapsResponse

    /// See `CrossNetworkAutomationServiceClient.getServiceConnectionMap`.
    func getServiceConnectionMap(
      request: GetServiceConnectionMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceConnectionMap

    /// See `CrossNetworkAutomationServiceClient.createServiceConnectionMap`.
    func createServiceConnectionMap(
      request: CreateServiceConnectionMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CrossNetworkAutomationServiceClient.createServiceConnectionMap`.
    func createServiceConnectionMapPollingUntilDone(
      request: CreateServiceConnectionMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> ServiceConnectionMap

    /// See `CrossNetworkAutomationServiceClient.updateServiceConnectionMap`.
    func updateServiceConnectionMap(
      request: UpdateServiceConnectionMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CrossNetworkAutomationServiceClient.updateServiceConnectionMap`.
    func updateServiceConnectionMapPollingUntilDone(
      request: UpdateServiceConnectionMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> ServiceConnectionMap

    /// See `CrossNetworkAutomationServiceClient.deleteServiceConnectionMap`.
    func deleteServiceConnectionMap(
      request: DeleteServiceConnectionMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CrossNetworkAutomationServiceClient.deleteServiceConnectionMap`.
    func deleteServiceConnectionMapPollingUntilDone(
      request: DeleteServiceConnectionMapRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `CrossNetworkAutomationServiceClient.listServiceConnectionPolicies`.
    func listServiceConnectionPolicies(
      request: ListServiceConnectionPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionPoliciesResponse

    /// See `CrossNetworkAutomationServiceClient.getServiceConnectionPolicy`.
    func getServiceConnectionPolicy(
      request: GetServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceConnectionPolicy

    /// See `CrossNetworkAutomationServiceClient.createServiceConnectionPolicy`.
    func createServiceConnectionPolicy(
      request: CreateServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CrossNetworkAutomationServiceClient.createServiceConnectionPolicy`.
    func createServiceConnectionPolicyPollingUntilDone(
      request: CreateServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> ServiceConnectionPolicy

    /// See `CrossNetworkAutomationServiceClient.updateServiceConnectionPolicy`.
    func updateServiceConnectionPolicy(
      request: UpdateServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CrossNetworkAutomationServiceClient.updateServiceConnectionPolicy`.
    func updateServiceConnectionPolicyPollingUntilDone(
      request: UpdateServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> ServiceConnectionPolicy

    /// See `CrossNetworkAutomationServiceClient.deleteServiceConnectionPolicy`.
    func deleteServiceConnectionPolicy(
      request: DeleteServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CrossNetworkAutomationServiceClient.deleteServiceConnectionPolicy`.
    func deleteServiceConnectionPolicyPollingUntilDone(
      request: DeleteServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `CrossNetworkAutomationServiceClient.listServiceClasses`.
    func listServiceClasses(
      request: ListServiceClassesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceClassesResponse

    /// See `CrossNetworkAutomationServiceClient.getServiceClass`.
    func getServiceClass(
      request: GetServiceClassRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceClass

    /// See `CrossNetworkAutomationServiceClient.updateServiceClass`.
    func updateServiceClass(
      request: UpdateServiceClassRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CrossNetworkAutomationServiceClient.updateServiceClass`.
    func updateServiceClassPollingUntilDone(
      request: UpdateServiceClassRequest, options: GoogleGax.RequestOptions
    ) async throws -> ServiceClass

    /// See `CrossNetworkAutomationServiceClient.deleteServiceClass`.
    func deleteServiceClass(
      request: DeleteServiceClassRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CrossNetworkAutomationServiceClient.deleteServiceClass`.
    func deleteServiceClassPollingUntilDone(
      request: DeleteServiceClassRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `CrossNetworkAutomationServiceClient.getServiceConnectionToken`.
    func getServiceConnectionToken(
      request: GetServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceConnectionToken

    /// See `CrossNetworkAutomationServiceClient.listServiceConnectionTokens`.
    func listServiceConnectionTokens(
      request: ListServiceConnectionTokensRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionTokensResponse

    /// See `CrossNetworkAutomationServiceClient.createServiceConnectionToken`.
    func createServiceConnectionToken(
      request: CreateServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CrossNetworkAutomationServiceClient.createServiceConnectionToken`.
    func createServiceConnectionTokenPollingUntilDone(
      request: CreateServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> ServiceConnectionToken

    /// See `CrossNetworkAutomationServiceClient.deleteServiceConnectionToken`.
    func deleteServiceConnectionToken(
      request: DeleteServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CrossNetworkAutomationServiceClient.deleteServiceConnectionToken`.
    func deleteServiceConnectionTokenPollingUntilDone(
      request: DeleteServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `CrossNetworkAutomationServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `CrossNetworkAutomationServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `CrossNetworkAutomationServiceClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `CrossNetworkAutomationServiceClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `CrossNetworkAutomationServiceClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `CrossNetworkAutomationServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `CrossNetworkAutomationServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `CrossNetworkAutomationServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.CrossNetworkAutomationServiceProtocol {
  public func listServiceConnectionMaps(request: ListServiceConnectionMapsRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionMapsResponse
  {
    try await self.listServiceConnectionMaps(request: request, options: .init())
  }

  public func listServiceConnectionMaps(
    request: ListServiceConnectionMapsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionMapsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listServiceConnectionMapsByItems(
    request: ListServiceConnectionMapsRequest
  ) -> some AsyncSequence<ServiceConnectionMap, Swift.Error> & Sendable {
    self.listServiceConnectionMapsByItems(request: request, options: .init())
  }

  /// Lists ServiceConnectionMaps in a given project and location.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_ListServiceConnectionMaps")
  public func listServiceConnectionMapsByItems(
    request: ListServiceConnectionMapsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<ServiceConnectionMap, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionMapsResponse in
      var request = request
      request.pageToken = token
      return try await self.listServiceConnectionMaps(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listServiceConnectionMapsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<ServiceConnectionMap, Swift.Error> & Sendable {
    let request = ListServiceConnectionMapsRequest().with {
      $0.parent = parent
    }
    return self.listServiceConnectionMapsByItems(request: request)
  }

  public func getServiceConnectionMap(request: GetServiceConnectionMapRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.ServiceConnectionMap
  {
    try await self.getServiceConnectionMap(request: request, options: .init())
  }

  public func getServiceConnectionMap(
    request: GetServiceConnectionMapRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceConnectionMap {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getServiceConnectionMap(
    name: Swift.String,
  ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceConnectionMap {
    let request = GetServiceConnectionMapRequest().with {
      $0.name = name
    }
    return try await self.getServiceConnectionMap(request: request)
  }

  public func createServiceConnectionMap(request: CreateServiceConnectionMapRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createServiceConnectionMap(request: request, options: .init())
  }

  public func createServiceConnectionMap(
    request: CreateServiceConnectionMapRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createServiceConnectionMapPollingUntilDone(request: CreateServiceConnectionMapRequest)
    async throws -> ServiceConnectionMap
  {
    return try await self.createServiceConnectionMapPollingUntilDone(
      request: request, options: .init())
  }

  public func createServiceConnectionMapPollingUntilDone(
    request: CreateServiceConnectionMapRequest, options: GoogleGax.RequestOptions
  ) async throws -> ServiceConnectionMap {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createServiceConnectionMapPollingUntilDone(
    parent: Swift.String,
    serviceConnectionMap: ServiceConnectionMap?,
    serviceConnectionMapId: Swift.String,
  ) async throws -> ServiceConnectionMap {
    let request = CreateServiceConnectionMapRequest().with {
      $0.parent = parent
      $0.serviceConnectionMap = serviceConnectionMap
      $0.serviceConnectionMapId = serviceConnectionMapId
    }
    return try await self.createServiceConnectionMapPollingUntilDone(request: request)
  }

  public func updateServiceConnectionMap(request: UpdateServiceConnectionMapRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateServiceConnectionMap(request: request, options: .init())
  }

  public func updateServiceConnectionMap(
    request: UpdateServiceConnectionMapRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateServiceConnectionMapPollingUntilDone(request: UpdateServiceConnectionMapRequest)
    async throws -> ServiceConnectionMap
  {
    return try await self.updateServiceConnectionMapPollingUntilDone(
      request: request, options: .init())
  }

  public func updateServiceConnectionMapPollingUntilDone(
    request: UpdateServiceConnectionMapRequest, options: GoogleGax.RequestOptions
  ) async throws -> ServiceConnectionMap {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateServiceConnectionMapPollingUntilDone(
    serviceConnectionMap: ServiceConnectionMap?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> ServiceConnectionMap {
    let request = UpdateServiceConnectionMapRequest().with {
      $0.serviceConnectionMap = serviceConnectionMap
      $0.updateMask = updateMask
    }
    return try await self.updateServiceConnectionMapPollingUntilDone(request: request)
  }

  public func deleteServiceConnectionMap(request: DeleteServiceConnectionMapRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteServiceConnectionMap(request: request, options: .init())
  }

  public func deleteServiceConnectionMap(
    request: DeleteServiceConnectionMapRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteServiceConnectionMapPollingUntilDone(request: DeleteServiceConnectionMapRequest)
    async throws
  {
    try await self.deleteServiceConnectionMapPollingUntilDone(request: request, options: .init())
  }

  public func deleteServiceConnectionMapPollingUntilDone(
    request: DeleteServiceConnectionMapRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteServiceConnectionMapPollingUntilDone(
    name: Swift.String,
  ) async throws {
    let request = DeleteServiceConnectionMapRequest().with {
      $0.name = name
    }
    try await self.deleteServiceConnectionMapPollingUntilDone(request: request)
  }

  public func listServiceConnectionPolicies(request: ListServiceConnectionPoliciesRequest)
    async throws -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionPoliciesResponse
  {
    try await self.listServiceConnectionPolicies(request: request, options: .init())
  }

  public func listServiceConnectionPolicies(
    request: ListServiceConnectionPoliciesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionPoliciesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listServiceConnectionPoliciesByItems(
    request: ListServiceConnectionPoliciesRequest
  ) -> some AsyncSequence<ServiceConnectionPolicy, Swift.Error> & Sendable {
    self.listServiceConnectionPoliciesByItems(request: request, options: .init())
  }

  /// Lists ServiceConnectionPolicies in a given project and location.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_ListServiceConnectionPolicies")
  public func listServiceConnectionPoliciesByItems(
    request: ListServiceConnectionPoliciesRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<ServiceConnectionPolicy, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionPoliciesResponse in
      var request = request
      request.pageToken = token
      return try await self.listServiceConnectionPolicies(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listServiceConnectionPoliciesByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<ServiceConnectionPolicy, Swift.Error> & Sendable {
    let request = ListServiceConnectionPoliciesRequest().with {
      $0.parent = parent
    }
    return self.listServiceConnectionPoliciesByItems(request: request)
  }

  public func getServiceConnectionPolicy(request: GetServiceConnectionPolicyRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.ServiceConnectionPolicy
  {
    try await self.getServiceConnectionPolicy(request: request, options: .init())
  }

  public func getServiceConnectionPolicy(
    request: GetServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceConnectionPolicy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getServiceConnectionPolicy(
    name: Swift.String,
  ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceConnectionPolicy {
    let request = GetServiceConnectionPolicyRequest().with {
      $0.name = name
    }
    return try await self.getServiceConnectionPolicy(request: request)
  }

  public func createServiceConnectionPolicy(request: CreateServiceConnectionPolicyRequest)
    async throws -> GoogleLongRunning.Operation
  {
    try await self.createServiceConnectionPolicy(request: request, options: .init())
  }

  public func createServiceConnectionPolicy(
    request: CreateServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createServiceConnectionPolicyPollingUntilDone(
    request: CreateServiceConnectionPolicyRequest
  ) async throws -> ServiceConnectionPolicy {
    return try await self.createServiceConnectionPolicyPollingUntilDone(
      request: request, options: .init())
  }

  public func createServiceConnectionPolicyPollingUntilDone(
    request: CreateServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> ServiceConnectionPolicy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createServiceConnectionPolicyPollingUntilDone(
    parent: Swift.String,
    serviceConnectionPolicy: ServiceConnectionPolicy?,
    serviceConnectionPolicyId: Swift.String,
  ) async throws -> ServiceConnectionPolicy {
    let request = CreateServiceConnectionPolicyRequest().with {
      $0.parent = parent
      $0.serviceConnectionPolicy = serviceConnectionPolicy
      $0.serviceConnectionPolicyId = serviceConnectionPolicyId
    }
    return try await self.createServiceConnectionPolicyPollingUntilDone(request: request)
  }

  public func updateServiceConnectionPolicy(request: UpdateServiceConnectionPolicyRequest)
    async throws -> GoogleLongRunning.Operation
  {
    try await self.updateServiceConnectionPolicy(request: request, options: .init())
  }

  public func updateServiceConnectionPolicy(
    request: UpdateServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateServiceConnectionPolicyPollingUntilDone(
    request: UpdateServiceConnectionPolicyRequest
  ) async throws -> ServiceConnectionPolicy {
    return try await self.updateServiceConnectionPolicyPollingUntilDone(
      request: request, options: .init())
  }

  public func updateServiceConnectionPolicyPollingUntilDone(
    request: UpdateServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> ServiceConnectionPolicy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateServiceConnectionPolicyPollingUntilDone(
    serviceConnectionPolicy: ServiceConnectionPolicy?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> ServiceConnectionPolicy {
    let request = UpdateServiceConnectionPolicyRequest().with {
      $0.serviceConnectionPolicy = serviceConnectionPolicy
      $0.updateMask = updateMask
    }
    return try await self.updateServiceConnectionPolicyPollingUntilDone(request: request)
  }

  public func deleteServiceConnectionPolicy(request: DeleteServiceConnectionPolicyRequest)
    async throws -> GoogleLongRunning.Operation
  {
    try await self.deleteServiceConnectionPolicy(request: request, options: .init())
  }

  public func deleteServiceConnectionPolicy(
    request: DeleteServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteServiceConnectionPolicyPollingUntilDone(
    request: DeleteServiceConnectionPolicyRequest
  ) async throws {
    try await self.deleteServiceConnectionPolicyPollingUntilDone(request: request, options: .init())
  }

  public func deleteServiceConnectionPolicyPollingUntilDone(
    request: DeleteServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteServiceConnectionPolicyPollingUntilDone(
    name: Swift.String,
  ) async throws {
    let request = DeleteServiceConnectionPolicyRequest().with {
      $0.name = name
    }
    try await self.deleteServiceConnectionPolicyPollingUntilDone(request: request)
  }

  public func listServiceClasses(request: ListServiceClassesRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.ListServiceClassesResponse
  {
    try await self.listServiceClasses(request: request, options: .init())
  }

  public func listServiceClasses(
    request: ListServiceClassesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceClassesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listServiceClassesByItems(
    request: ListServiceClassesRequest
  ) -> some AsyncSequence<ServiceClass, Swift.Error> & Sendable {
    self.listServiceClassesByItems(request: request, options: .init())
  }

  /// Lists ServiceClasses in a given project and location.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_ListServiceClasses")
  public func listServiceClassesByItems(
    request: ListServiceClassesRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<ServiceClass, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudNetworkConnectivityV1.ListServiceClassesResponse in
      var request = request
      request.pageToken = token
      return try await self.listServiceClasses(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listServiceClassesByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<ServiceClass, Swift.Error> & Sendable {
    let request = ListServiceClassesRequest().with {
      $0.parent = parent
    }
    return self.listServiceClassesByItems(request: request)
  }

  public func getServiceClass(request: GetServiceClassRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.ServiceClass
  {
    try await self.getServiceClass(request: request, options: .init())
  }

  public func getServiceClass(
    request: GetServiceClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceClass {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getServiceClass(
    name: Swift.String,
  ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceClass {
    let request = GetServiceClassRequest().with {
      $0.name = name
    }
    return try await self.getServiceClass(request: request)
  }

  public func updateServiceClass(request: UpdateServiceClassRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateServiceClass(request: request, options: .init())
  }

  public func updateServiceClass(
    request: UpdateServiceClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateServiceClassPollingUntilDone(request: UpdateServiceClassRequest) async throws
    -> ServiceClass
  {
    return try await self.updateServiceClassPollingUntilDone(request: request, options: .init())
  }

  public func updateServiceClassPollingUntilDone(
    request: UpdateServiceClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> ServiceClass {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateServiceClassPollingUntilDone(
    serviceClass: ServiceClass?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> ServiceClass {
    let request = UpdateServiceClassRequest().with {
      $0.serviceClass = serviceClass
      $0.updateMask = updateMask
    }
    return try await self.updateServiceClassPollingUntilDone(request: request)
  }

  public func deleteServiceClass(request: DeleteServiceClassRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteServiceClass(request: request, options: .init())
  }

  public func deleteServiceClass(
    request: DeleteServiceClassRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteServiceClassPollingUntilDone(request: DeleteServiceClassRequest) async throws {
    try await self.deleteServiceClassPollingUntilDone(request: request, options: .init())
  }

  public func deleteServiceClassPollingUntilDone(
    request: DeleteServiceClassRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteServiceClassPollingUntilDone(
    name: Swift.String,
  ) async throws {
    let request = DeleteServiceClassRequest().with {
      $0.name = name
    }
    try await self.deleteServiceClassPollingUntilDone(request: request)
  }

  public func getServiceConnectionToken(request: GetServiceConnectionTokenRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.ServiceConnectionToken
  {
    try await self.getServiceConnectionToken(request: request, options: .init())
  }

  public func getServiceConnectionToken(
    request: GetServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceConnectionToken {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getServiceConnectionToken(
    name: Swift.String,
  ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceConnectionToken {
    let request = GetServiceConnectionTokenRequest().with {
      $0.name = name
    }
    return try await self.getServiceConnectionToken(request: request)
  }

  public func listServiceConnectionTokens(request: ListServiceConnectionTokensRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionTokensResponse
  {
    try await self.listServiceConnectionTokens(request: request, options: .init())
  }

  public func listServiceConnectionTokens(
    request: ListServiceConnectionTokensRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionTokensResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listServiceConnectionTokensByItems(
    request: ListServiceConnectionTokensRequest
  ) -> some AsyncSequence<ServiceConnectionToken, Swift.Error> & Sendable {
    self.listServiceConnectionTokensByItems(request: request, options: .init())
  }

  /// Lists ServiceConnectionTokens in a given project and location.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_ListServiceConnectionTokens")
  public func listServiceConnectionTokensByItems(
    request: ListServiceConnectionTokensRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<ServiceConnectionToken, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionTokensResponse in
      var request = request
      request.pageToken = token
      return try await self.listServiceConnectionTokens(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listServiceConnectionTokensByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<ServiceConnectionToken, Swift.Error> & Sendable {
    let request = ListServiceConnectionTokensRequest().with {
      $0.parent = parent
    }
    return self.listServiceConnectionTokensByItems(request: request)
  }

  public func createServiceConnectionToken(request: CreateServiceConnectionTokenRequest)
    async throws -> GoogleLongRunning.Operation
  {
    try await self.createServiceConnectionToken(request: request, options: .init())
  }

  public func createServiceConnectionToken(
    request: CreateServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createServiceConnectionTokenPollingUntilDone(
    request: CreateServiceConnectionTokenRequest
  ) async throws -> ServiceConnectionToken {
    return try await self.createServiceConnectionTokenPollingUntilDone(
      request: request, options: .init())
  }

  public func createServiceConnectionTokenPollingUntilDone(
    request: CreateServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> ServiceConnectionToken {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createServiceConnectionTokenPollingUntilDone(
    parent: Swift.String,
    serviceConnectionToken: ServiceConnectionToken?,
    serviceConnectionTokenId: Swift.String,
  ) async throws -> ServiceConnectionToken {
    let request = CreateServiceConnectionTokenRequest().with {
      $0.parent = parent
      $0.serviceConnectionToken = serviceConnectionToken
      $0.serviceConnectionTokenId = serviceConnectionTokenId
    }
    return try await self.createServiceConnectionTokenPollingUntilDone(request: request)
  }

  public func deleteServiceConnectionToken(request: DeleteServiceConnectionTokenRequest)
    async throws -> GoogleLongRunning.Operation
  {
    try await self.deleteServiceConnectionToken(request: request, options: .init())
  }

  public func deleteServiceConnectionToken(
    request: DeleteServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteServiceConnectionTokenPollingUntilDone(
    request: DeleteServiceConnectionTokenRequest
  ) async throws {
    try await self.deleteServiceConnectionTokenPollingUntilDone(request: request, options: .init())
  }

  public func deleteServiceConnectionTokenPollingUntilDone(
    request: DeleteServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteServiceConnectionTokenPollingUntilDone(
    name: Swift.String,
  ) async throws {
    let request = DeleteServiceConnectionTokenRequest().with {
      $0.name = name
    }
    try await self.deleteServiceConnectionTokenPollingUntilDone(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> some AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CrossNetworkAutomationService_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
