// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The `Destination` resource. It specifies the IP prefix and the associated
/// autonomous system numbers (ASN) that you want to include in a
/// `MulticloudDataTransferConfig` resource.
public struct Destination: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the `Destination` resource.
  /// Format:
  /// `projects/{project}/locations/{location}/multicloudDataTransferConfigs/{multicloud_data_transfer_config}/destinations/{destination}`.
  public var name: Swift.String = Swift.String()

  /// Output only. Time when the `Destination` resource was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Time when the `Destination` resource was updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. User-defined labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// The etag is computed by the server, and might be sent with update and
  /// delete requests so that the client has an up-to-date value before
  /// proceeding.
  public var etag: Swift.String = Swift.String()

  /// Optional. A description of this resource.
  public var description: Swift.String = Swift.String()

  /// Required. Immutable. The IP prefix that represents your workload on another
  /// CSP.
  public var ipPrefix: Swift.String = Swift.String()

  /// Required. Unordered list. The list of `DestinationEndpoint` resources
  /// configured for the IP prefix.
  public var endpoints: [Destination.DestinationEndpoint] = []

  /// Output only. The timeline of the expected `Destination` states or the
  /// current rest state. If a state change is expected, the value is `ADDING`,
  /// `DELETING` or `SUSPENDING`, depending on the action specified.
  ///
  /// Example:
  /// "state_timeline": {
  ///   "states": [
  ///     {
  ///       // The time when the `Destination` resource will be activated.
  ///       "effectiveTime": "2024-12-01T08:00:00Z",
  ///       "state": "ADDING"
  ///     },
  ///     {
  ///       // The time when the `Destination` resource will be suspended.
  ///       "effectiveTime": "2024-12-01T20:00:00Z",
  ///       "state": "SUSPENDING"
  ///     }
  ///   ]
  /// }
  public var stateTimeline: StateTimeline? = nil

  /// Output only. The Google-generated unique ID for the `Destination` resource.
  /// This value is unique across all `Destination` resources.
  /// If a resource is deleted and another with the same name is
  /// created, the new resource is assigned a different and unique ID.
  public var uid: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Destination`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Destination().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let etag = CodingKeys(stringValue: "etag")
    static let description = CodingKeys(stringValue: "description")
    static let ipPrefix = CodingKeys(stringValue: "ipPrefix")
    static let endpoints = CodingKeys(stringValue: "endpoints")
    static let stateTimeline = CodingKeys(stringValue: "stateTimeline")
    static let uid = CodingKeys(stringValue: "uid")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "etag",
      "description",
      "ipPrefix",
      "endpoints",
      "stateTimeline",
      "uid",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ipPrefix) {
      self.ipPrefix = value
    }
    if let value = try container.decodeIfPresent(
      [Destination.DestinationEndpoint].self, forKey: .endpoints)
    {
      self.endpoints = value
    }
    self.stateTimeline = try container.decodeIfPresent(StateTimeline.self, forKey: .stateTimeline)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.ipPrefix, forKey: .ipPrefix)
    try container.encode(self.endpoints, forKey: .endpoints)
    try container.encodeIfPresent(self.stateTimeline, forKey: .stateTimeline)
    try container.encode(self.uid, forKey: .uid)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The metadata for a `DestinationEndpoint` resource.
  public struct DestinationEndpoint: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The ASN of the remote IP prefix.
    public var asn: Swift.Int64 = Swift.Int64()

    /// Required. The CSP of the remote IP prefix.
    public var csp: Swift.String = Swift.String()

    /// Output only. The state of the `DestinationEndpoint` resource.
    public var state: Destination.DestinationEndpoint.State = Destination.DestinationEndpoint
      .State()

    /// Output only. Time when the `DestinationEndpoint` resource was updated.
    public var updateTime: GoogleWKT.WKTTimestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DestinationEndpoint`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DestinationEndpoint().with { $0.asn = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let asn = CodingKeys(stringValue: "asn")
      static let csp = CodingKeys(stringValue: "csp")
      static let state = CodingKeys(stringValue: "state")
      static let updateTime = CodingKeys(stringValue: "updateTime")

      static let _knownKeys: Set<Swift.String> = [
        "asn",
        "csp",
        "state",
        "updateTime",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .asn) {
        self.asn = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .csp) {
        self.csp = value
      }
      if let value = try container.decodeIfPresent(
        Destination.DestinationEndpoint.State.self, forKey: .state)
      {
        self.state = value
      }
      self.updateTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.asn, forKey: .asn)
      try container.encode(self.csp, forKey: .csp)
      try container.encode(self.state, forKey: .state)
      try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The state of the `DestinationEndpoint` resource.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum State: Codable, Equatable, Hashable, Sendable {
      /// An invalid state, which is the default case.
      case unspecified
      /// The `DestinationEndpoint` resource is valid.
      case valid
      /// The `DestinationEndpoint` resource is invalid.
      case invalid
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .valid: return 1
        case .invalid: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "STATE_UNSPECIFIED"
        case .valid: return "VALID"
        case .invalid: return "INVALID"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "STATE_UNSPECIFIED": self = .unspecified
        case "VALID": self = .valid
        case "INVALID": self = .invalid
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .valid
        case 2: self = .invalid
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("STATE_UNSPECIFIED")
        case .valid: return try container.encode("VALID")
        case .invalid: return try container.encode("INVALID")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The type URL for `DestinationEndpoint`: `"type.googleapis.com/google.cloud.networkconnectivity.v1.Destination.DestinationEndpoint"`.
    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.networkconnectivity.v1.Destination.DestinationEndpoint"
    }

    /// Initialize an instance of `DestinationEndpoint` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.networkconnectivity.v1.Destination.DestinationEndpoint"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `DestinationEndpoint` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The type URL for `Destination`: `"type.googleapis.com/google.cloud.networkconnectivity.v1.Destination"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.Destination"
  }

  /// Initialize an instance of `Destination` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.networkconnectivity.v1.Destination"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `Destination` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
