// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A hub status entry represents the status of a set of propagated Private
/// Service Connect connections grouped by certain fields.
public struct HubStatusEntry: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The number of propagated Private Service Connect connections with this
  /// status. If the `group_by` field was not set in the request message, the
  /// value of this field is 1.
  public var count: Swift.Int32 = Swift.Int32()

  /// The fields that this entry is grouped by. This has the same value as the
  /// `group_by` field in the request message.
  public var groupBy: Swift.String = Swift.String()

  /// The Private Service Connect propagation status.
  public var pscPropagationStatus: PscPropagationStatus? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `HubStatusEntry`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HubStatusEntry().with { $0.count = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let count = CodingKeys(stringValue: "count")
    static let groupBy = CodingKeys(stringValue: "groupBy")
    static let pscPropagationStatus = CodingKeys(stringValue: "pscPropagationStatus")

    static let _knownKeys: Set<Swift.String> = [
      "count",
      "groupBy",
      "pscPropagationStatus",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .count) {
      self.count = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .groupBy) {
      self.groupBy = value
    }
    self.pscPropagationStatus = try container.decodeIfPresent(
      PscPropagationStatus.self, forKey: .pscPropagationStatus)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.count, forKey: .count)
    try container.encode(self.groupBy, forKey: .groupBy)
    try container.encodeIfPresent(self.pscPropagationStatus, forKey: .pscPropagationStatus)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.HubStatusEntry"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
