// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The internal range resource for IPAM operations within a VPC network.
/// Used to represent a private address range along with behavioral
/// characteristics of that range (its usage and peering behavior).
/// Networking resources can link to this range if they are created
/// as belonging to it.
public struct InternalRange: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of an internal range.
  /// Format:
  /// projects/{project}/locations/{location}/internalRanges/{internal_range}
  /// See: https://google.aip.dev/122#fields-representing-resource-names
  public var name: Swift.String = Swift.String()

  /// Output only. Time when the internal range was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Time when the internal range was updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// User-defined labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. A description of this resource.
  public var description: Swift.String = Swift.String()

  /// Optional. The IP range that this internal range defines.
  /// NOTE: IPv6 ranges are limited to usage=EXTERNAL_TO_VPC and
  /// peering=FOR_SELF.
  /// NOTE: For IPv6 Ranges this field is compulsory, i.e. the address range must
  /// be specified explicitly.
  public var ipCidrRange: Swift.String = Swift.String()

  /// Immutable. The URL or resource ID of the network in which to reserve the
  /// internal range. The network cannot be deleted if there are any reserved
  /// internal ranges referring to it. Legacy networks are not supported. For
  /// example:
  ///   https://www.googleapis.com/compute/v1/projects/{project}/locations/global/networks/{network}
  ///   projects/{project}/locations/global/networks/{network}
  ///   {network}
  public var network: Swift.String = Swift.String()

  /// Optional. The type of usage set for this InternalRange.
  public var usage: InternalRange.Usage = InternalRange.Usage()

  /// Optional. The type of peering set for this internal range.
  public var peering: InternalRange.Peering = InternalRange.Peering()

  /// Optional. An alternate to ip_cidr_range. Can be set when trying to create
  /// an IPv4 reservation that automatically finds a free range of the given
  /// size. If both ip_cidr_range and prefix_length are set, there is an error if
  /// the range sizes do not match. Can also be used during updates to change the
  /// range size.
  /// NOTE: For IPv6 this field only works if ip_cidr_range is set as well, and
  /// both fields must match. In other words, with IPv6 this field only works as
  /// a redundant parameter.
  public var prefixLength: Swift.Int32 = Swift.Int32()

  /// Optional. Can be set to narrow down or pick a different address space while
  /// searching for a free range. If not set, defaults to the ["10.0.0.0/8",
  /// "172.16.0.0/12", "192.168.0.0/16"] address space (for auto-mode networks,
  /// the "10.0.0.0/9" range is used instead of "10.0.0.0/8"). This can be used
  /// to target the search in other rfc-1918 address spaces like "172.16.0.0/12"
  /// and "192.168.0.0/16" or non-rfc-1918 address spaces used in the VPC.
  public var targetCidrRange: [Swift.String] = []

  /// Output only. The list of resources that refer to this internal range.
  /// Resources that use the internal range for their range allocation
  /// are referred to as users of the range. Other resources mark themselves
  /// as users while doing so by creating a reference to this internal range.
  /// Having a user, based on this reference, prevents deletion of the
  /// internal range referred to. Can be empty.
  public var users: [Swift.String] = []

  /// Optional. Types of resources that are allowed to overlap with the current
  /// internal range.
  public var overlaps: [InternalRange.Overlap] = []

  /// Optional. Must be present if usage is set to FOR_MIGRATION.
  public var migration: InternalRange.Migration? = nil

  /// Optional. Immutable ranges cannot have their fields modified, except for
  /// labels and description.
  public var immutable: Swift.Bool = Swift.Bool()

  /// Optional. Range auto-allocation options, may be set only when
  /// auto-allocation is selected by not setting ip_cidr_range (and setting
  /// prefix_length).
  public var allocationOptions: InternalRange.AllocationOptions? = nil

  /// Optional. ExcludeCidrRanges flag. Specifies a set of CIDR blocks that
  /// allows exclusion of particular CIDR ranges from the auto-allocation
  /// process, without having to reserve these blocks
  public var excludeCidrRanges: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `InternalRange`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InternalRange().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let description = CodingKeys(stringValue: "description")
    static let ipCidrRange = CodingKeys(stringValue: "ipCidrRange")
    static let network = CodingKeys(stringValue: "network")
    static let usage = CodingKeys(stringValue: "usage")
    static let peering = CodingKeys(stringValue: "peering")
    static let prefixLength = CodingKeys(stringValue: "prefixLength")
    static let targetCidrRange = CodingKeys(stringValue: "targetCidrRange")
    static let users = CodingKeys(stringValue: "users")
    static let overlaps = CodingKeys(stringValue: "overlaps")
    static let migration = CodingKeys(stringValue: "migration")
    static let immutable = CodingKeys(stringValue: "immutable")
    static let allocationOptions = CodingKeys(stringValue: "allocationOptions")
    static let excludeCidrRanges = CodingKeys(stringValue: "excludeCidrRanges")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "description",
      "ipCidrRange",
      "network",
      "usage",
      "peering",
      "prefixLength",
      "targetCidrRange",
      "users",
      "overlaps",
      "migration",
      "immutable",
      "allocationOptions",
      "excludeCidrRanges",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ipCidrRange) {
      self.ipCidrRange = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
      self.network = value
    }
    if let value = try container.decodeIfPresent(InternalRange.Usage.self, forKey: .usage) {
      self.usage = value
    }
    if let value = try container.decodeIfPresent(InternalRange.Peering.self, forKey: .peering) {
      self.peering = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .prefixLength) {
      self.prefixLength = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .targetCidrRange) {
      self.targetCidrRange = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .users) {
      self.users = value
    }
    if let value = try container.decodeIfPresent([InternalRange.Overlap].self, forKey: .overlaps) {
      self.overlaps = value
    }
    self.migration = try container.decodeIfPresent(InternalRange.Migration.self, forKey: .migration)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .immutable) {
      self.immutable = value
    }
    self.allocationOptions = try container.decodeIfPresent(
      InternalRange.AllocationOptions.self, forKey: .allocationOptions)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .excludeCidrRanges) {
      self.excludeCidrRanges = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.ipCidrRange, forKey: .ipCidrRange)
    try container.encode(self.network, forKey: .network)
    try container.encode(self.usage, forKey: .usage)
    try container.encode(self.peering, forKey: .peering)
    try container.encode(self.prefixLength, forKey: .prefixLength)
    try container.encode(self.targetCidrRange, forKey: .targetCidrRange)
    try container.encode(self.users, forKey: .users)
    try container.encode(self.overlaps, forKey: .overlaps)
    try container.encodeIfPresent(self.migration, forKey: .migration)
    try container.encode(self.immutable, forKey: .immutable)
    try container.encodeIfPresent(self.allocationOptions, forKey: .allocationOptions)
    try container.encode(self.excludeCidrRanges, forKey: .excludeCidrRanges)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Specification for migration with source and target resource names.
  public struct Migration: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Immutable. Resource path as an URI of the source resource, for example a
    /// subnet. The project for the source resource should match the project for
    /// the InternalRange. An example:
    ///   /projects/{project}/regions/{region}/subnetworks/{subnet}
    public var source: Swift.String = Swift.String()

    /// Immutable. Resource path of the target resource. The target project can
    /// be different, as in the cases when migrating to peer networks. For
    /// example:
    ///   /projects/{project}/regions/{region}/subnetworks/{subnet}
    public var target: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Migration`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Migration().with { $0.source = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let source = CodingKeys(stringValue: "source")
      static let target = CodingKeys(stringValue: "target")

      static let _knownKeys: Set<Swift.String> = [
        "source",
        "target",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .source) {
        self.source = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .target) {
        self.target = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.source, forKey: .source)
      try container.encode(self.target, forKey: .target)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `Migration`: `"type.googleapis.com/google.cloud.networkconnectivity.v1.InternalRange.Migration"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.networkconnectivity.v1.InternalRange.Migration"
    }

    /// Initialize an instance of `Migration` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.networkconnectivity.v1.InternalRange.Migration"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `Migration` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Range auto-allocation options, to be optionally used when CIDR block is not
  /// explicitly set.
  public struct AllocationOptions: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Allocation strategy Not setting this field when the allocation
    /// is requested means an implementation defined strategy is used.
    public var allocationStrategy: InternalRange.AllocationStrategy =
      InternalRange.AllocationStrategy()

    /// Optional. This field must be set only when allocation_strategy is set to
    /// RANDOM_FIRST_N_AVAILABLE.
    /// The value should be the maximum expected parallelism of range creation
    /// requests issued to the same space of peered netwroks.
    public var firstAvailableRangesLookupSize: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AllocationOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AllocationOptions().with { $0.allocationStrategy = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let allocationStrategy = CodingKeys(stringValue: "allocationStrategy")
      static let firstAvailableRangesLookupSize = CodingKeys(
        stringValue: "firstAvailableRangesLookupSize")

      static let _knownKeys: Set<Swift.String> = [
        "allocationStrategy",
        "firstAvailableRangesLookupSize",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        InternalRange.AllocationStrategy.self, forKey: .allocationStrategy)
      {
        self.allocationStrategy = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Int32.self, forKey: .firstAvailableRangesLookupSize)
      {
        self.firstAvailableRangesLookupSize = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.allocationStrategy, forKey: .allocationStrategy)
      try container.encode(
        self.firstAvailableRangesLookupSize, forKey: .firstAvailableRangesLookupSize)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `AllocationOptions`: `"type.googleapis.com/google.cloud.networkconnectivity.v1.InternalRange.AllocationOptions"`.
    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.networkconnectivity.v1.InternalRange.AllocationOptions"
    }

    /// Initialize an instance of `AllocationOptions` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.networkconnectivity.v1.InternalRange.AllocationOptions"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `AllocationOptions` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Possible usage of an internal range.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Usage: Codable, Equatable, Hashable, Sendable {
    /// Unspecified usage is allowed in calls which identify the resource by
    /// other fields and do not need Usage set to complete. These are, i.e.:
    /// GetInternalRange and DeleteInternalRange.
    /// Usage needs to be specified explicitly in CreateInternalRange
    /// or UpdateInternalRange calls.
    case unspecified
    /// A VPC resource can use the reserved CIDR block by associating it with the
    /// internal range resource if usage is set to FOR_VPC.
    case forVpc
    /// Ranges created with EXTERNAL_TO_VPC cannot be associated with VPC
    /// resources and are meant to block out address ranges for various use
    /// cases, like for example, usage on-prem, with dynamic route announcements
    /// via interconnect.
    case externalToVpc
    /// Ranges created FOR_MIGRATION can be used to lock a CIDR range between a
    /// source and target subnet. If usage is set to FOR_MIGRATION, the peering
    /// value has to be set to FOR_SELF or default to FOR_SELF when unset.
    case forMigration
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .forVpc: return 1
      case .externalToVpc: return 2
      case .forMigration: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "USAGE_UNSPECIFIED"
      case .forVpc: return "FOR_VPC"
      case .externalToVpc: return "EXTERNAL_TO_VPC"
      case .forMigration: return "FOR_MIGRATION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Usage/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "USAGE_UNSPECIFIED": self = .unspecified
      case "FOR_VPC": self = .forVpc
      case "EXTERNAL_TO_VPC": self = .externalToVpc
      case "FOR_MIGRATION": self = .forMigration
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Usage/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .forVpc
      case 2: self = .externalToVpc
      case 3: self = .forMigration
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("USAGE_UNSPECIFIED")
      case .forVpc: return try container.encode("FOR_VPC")
      case .externalToVpc: return try container.encode("EXTERNAL_TO_VPC")
      case .forMigration: return try container.encode("FOR_MIGRATION")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Peering type.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Peering: Codable, Equatable, Hashable, Sendable {
    /// If Peering is left unspecified in CreateInternalRange or
    /// UpdateInternalRange, it will be defaulted to FOR_SELF.
    case unspecified
    /// This is the default behavior and represents the case that this
    /// internal range is intended to be used in the VPC in which it is created
    /// and is accessible from its peers. This implies that peers or
    /// peers-of-peers cannot use this range.
    case forSelf
    /// This behavior can be set when the internal range is being reserved for
    /// usage by peers. This means that no resource within the VPC in which
    /// it is being created can use this to associate with a VPC resource, but
    /// one of the peers can. This represents donating a range for peers to
    /// use.
    case forPeer
    /// This behavior can be set when the internal range is being reserved for
    /// usage by the VPC in which it is created, but not shared with peers.
    /// In a sense, it is local to the VPC. This can be used to create internal
    /// ranges for various purposes like HTTP_INTERNAL_LOAD_BALANCER or for
    /// Interconnect routes that are not shared with peers. This also implies
    /// that peers cannot use this range in a way that is visible to this VPC,
    /// but can re-use this range as long as it is NOT_SHARED from the peer VPC,
    /// too.
    case notShared
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .forSelf: return 1
      case .forPeer: return 2
      case .notShared: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PEERING_UNSPECIFIED"
      case .forSelf: return "FOR_SELF"
      case .forPeer: return "FOR_PEER"
      case .notShared: return "NOT_SHARED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Peering/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PEERING_UNSPECIFIED": self = .unspecified
      case "FOR_SELF": self = .forSelf
      case "FOR_PEER": self = .forPeer
      case "NOT_SHARED": self = .notShared
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Peering/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .forSelf
      case 2: self = .forPeer
      case 3: self = .notShared
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("PEERING_UNSPECIFIED")
      case .forSelf: return try container.encode("FOR_SELF")
      case .forPeer: return try container.encode("FOR_PEER")
      case .notShared: return try container.encode("NOT_SHARED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Overlap specifications.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Overlap: Codable, Equatable, Hashable, Sendable {
    /// No overlap overrides.
    case unspecified
    /// Allow creation of static routes more specific that the current
    /// internal range.
    case routeRange
    /// Allow creation of internal ranges that overlap with existing subnets.
    case existingSubnetRange
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .routeRange: return 1
      case .existingSubnetRange: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "OVERLAP_UNSPECIFIED"
      case .routeRange: return "OVERLAP_ROUTE_RANGE"
      case .existingSubnetRange: return "OVERLAP_EXISTING_SUBNET_RANGE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Overlap/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "OVERLAP_UNSPECIFIED": self = .unspecified
      case "OVERLAP_ROUTE_RANGE": self = .routeRange
      case "OVERLAP_EXISTING_SUBNET_RANGE": self = .existingSubnetRange
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Overlap/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .routeRange
      case 2: self = .existingSubnetRange
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("OVERLAP_UNSPECIFIED")
      case .routeRange: return try container.encode("OVERLAP_ROUTE_RANGE")
      case .existingSubnetRange: return try container.encode("OVERLAP_EXISTING_SUBNET_RANGE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Enumeration of range auto-allocation strategies
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum AllocationStrategy: Codable, Equatable, Hashable, Sendable {
    /// Unspecified is the only valid option when the range is specified
    /// explicitly by ip_cidr_range field. Otherwise unspefified means using the
    /// default strategy.
    case unspecified
    /// Random strategy, the legacy algorithm, used for backwards compatibility.
    /// This allocation strategy remains efficient in the case of concurrent
    /// allocation requests in the same peered network space and doesn't require
    /// providing the level of concurrency in an explicit parameter, but it is
    /// prone to fragmenting available address space.
    case random
    /// Pick the first available address range. This strategy is deterministic
    /// and the result is easy to predict.
    case firstAvailable
    /// Pick an arbitrary range out of the first N available ones. The N will be
    /// set in the first_available_ranges_lookup_size field. This strategy should
    /// be used when concurrent allocation requests are made in the same space of
    /// peered networks while the fragmentation of the addrress space is reduced.
    case randomFirstNAvailable
    /// Pick the smallest but fitting available range. This deterministic
    /// strategy minimizes fragmentation of the address space.
    case firstSmallestFitting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .random: return 1
      case .firstAvailable: return 2
      case .randomFirstNAvailable: return 3
      case .firstSmallestFitting: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ALLOCATION_STRATEGY_UNSPECIFIED"
      case .random: return "RANDOM"
      case .firstAvailable: return "FIRST_AVAILABLE"
      case .randomFirstNAvailable: return "RANDOM_FIRST_N_AVAILABLE"
      case .firstSmallestFitting: return "FIRST_SMALLEST_FITTING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AllocationStrategy/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ALLOCATION_STRATEGY_UNSPECIFIED": self = .unspecified
      case "RANDOM": self = .random
      case "FIRST_AVAILABLE": self = .firstAvailable
      case "RANDOM_FIRST_N_AVAILABLE": self = .randomFirstNAvailable
      case "FIRST_SMALLEST_FITTING": self = .firstSmallestFitting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AllocationStrategy/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .random
      case 2: self = .firstAvailable
      case 3: self = .randomFirstNAvailable
      case 4: self = .firstSmallestFitting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("ALLOCATION_STRATEGY_UNSPECIFIED")
      case .random: return try container.encode("RANDOM")
      case .firstAvailable: return try container.encode("FIRST_AVAILABLE")
      case .randomFirstNAvailable: return try container.encode("RANDOM_FIRST_N_AVAILABLE")
      case .firstSmallestFitting: return try container.encode("FIRST_SMALLEST_FITTING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `InternalRange`: `"type.googleapis.com/google.cloud.networkconnectivity.v1.InternalRange"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.InternalRange"
  }

  /// Initialize an instance of `InternalRange` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.networkconnectivity.v1.InternalRange"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `InternalRange` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
