// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

public struct LinkedProducerVpcNetwork: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Immutable. The URI of the Service Consumer VPC that the Producer VPC is
  /// peered with.
  public var network: Swift.String = Swift.String()

  /// Output only. The Service Consumer Network spoke.
  public var serviceConsumerVpcSpoke: Swift.String = Swift.String()

  /// Immutable. The name of the VPC peering between the Service Consumer VPC and
  /// the Producer VPC (defined in the Tenant project) which is added to the NCC
  /// hub. This peering must be in ACTIVE state.
  public var peering: Swift.String = Swift.String()

  /// Output only. The URI of the Producer VPC.
  public var producerNetwork: Swift.String = Swift.String()

  /// Optional. IP ranges encompassing the subnets to be excluded from peering.
  public var excludeExportRanges: [Swift.String] = []

  /// Optional. IP ranges allowed to be included from peering.
  public var includeExportRanges: [Swift.String] = []

  /// Optional. The proposed include export IP ranges waiting for hub
  /// administration's approval.
  public var proposedIncludeExportRanges: [Swift.String] = []

  /// Output only. The proposed exclude export IP ranges waiting for hub
  /// administration's approval.
  public var proposedExcludeExportRanges: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LinkedProducerVpcNetwork`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LinkedProducerVpcNetwork().with { $0.network = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let network = CodingKeys(stringValue: "network")
    static let serviceConsumerVpcSpoke = CodingKeys(stringValue: "serviceConsumerVpcSpoke")
    static let peering = CodingKeys(stringValue: "peering")
    static let producerNetwork = CodingKeys(stringValue: "producerNetwork")
    static let excludeExportRanges = CodingKeys(stringValue: "excludeExportRanges")
    static let includeExportRanges = CodingKeys(stringValue: "includeExportRanges")
    static let proposedIncludeExportRanges = CodingKeys(stringValue: "proposedIncludeExportRanges")
    static let proposedExcludeExportRanges = CodingKeys(stringValue: "proposedExcludeExportRanges")

    static let _knownKeys: Set<Swift.String> = [
      "network",
      "serviceConsumerVpcSpoke",
      "peering",
      "producerNetwork",
      "excludeExportRanges",
      "includeExportRanges",
      "proposedIncludeExportRanges",
      "proposedExcludeExportRanges",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
      self.network = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .serviceConsumerVpcSpoke)
    {
      self.serviceConsumerVpcSpoke = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .peering) {
      self.peering = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .producerNetwork) {
      self.producerNetwork = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .excludeExportRanges)
    {
      self.excludeExportRanges = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .includeExportRanges)
    {
      self.includeExportRanges = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .proposedIncludeExportRanges)
    {
      self.proposedIncludeExportRanges = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .proposedExcludeExportRanges)
    {
      self.proposedExcludeExportRanges = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.network, forKey: .network)
    try container.encode(self.serviceConsumerVpcSpoke, forKey: .serviceConsumerVpcSpoke)
    try container.encode(self.peering, forKey: .peering)
    try container.encode(self.producerNetwork, forKey: .producerNetwork)
    try container.encode(self.excludeExportRanges, forKey: .excludeExportRanges)
    try container.encode(self.includeExportRanges, forKey: .includeExportRanges)
    try container.encode(self.proposedIncludeExportRanges, forKey: .proposedIncludeExportRanges)
    try container.encode(self.proposedExcludeExportRanges, forKey: .proposedExcludeExportRanges)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.LinkedProducerVpcNetwork"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
