// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An existing VPC network.
public struct LinkedVpcNetwork: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The URI of the VPC network resource.
  public var uri: Swift.String = Swift.String()

  /// Optional. IP ranges encompassing the subnets to be excluded from peering.
  public var excludeExportRanges: [Swift.String] = []

  /// Optional. IP ranges allowed to be included from peering.
  public var includeExportRanges: [Swift.String] = []

  /// Optional. The proposed include export IP ranges waiting for hub
  /// administration's approval.
  public var proposedIncludeExportRanges: [Swift.String] = []

  /// Output only. The proposed exclude export IP ranges waiting for hub
  /// administration's approval.
  public var proposedExcludeExportRanges: [Swift.String] = []

  /// Output only. The list of Producer VPC spokes that this VPC spoke is a
  /// service consumer VPC spoke for. These producer VPCs are connected through
  /// VPC peering to this spoke's backing VPC network. Because they are directly
  /// connected throuh VPC peering, NCC export filters do not apply between the
  /// service consumer VPC spoke and any of its producer VPC spokes. This VPC
  /// spoke cannot be deleted as long as any of these producer VPC spokes are
  /// connected to the NCC Hub.
  public var producerVpcSpokes: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LinkedVpcNetwork`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LinkedVpcNetwork().with { $0.uri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let uri = CodingKeys(stringValue: "uri")
    static let excludeExportRanges = CodingKeys(stringValue: "excludeExportRanges")
    static let includeExportRanges = CodingKeys(stringValue: "includeExportRanges")
    static let proposedIncludeExportRanges = CodingKeys(stringValue: "proposedIncludeExportRanges")
    static let proposedExcludeExportRanges = CodingKeys(stringValue: "proposedExcludeExportRanges")
    static let producerVpcSpokes = CodingKeys(stringValue: "producerVpcSpokes")

    static let _knownKeys: Set<Swift.String> = [
      "uri",
      "excludeExportRanges",
      "includeExportRanges",
      "proposedIncludeExportRanges",
      "proposedExcludeExportRanges",
      "producerVpcSpokes",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
      self.uri = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .excludeExportRanges)
    {
      self.excludeExportRanges = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .includeExportRanges)
    {
      self.includeExportRanges = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .proposedIncludeExportRanges)
    {
      self.proposedIncludeExportRanges = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .proposedExcludeExportRanges)
    {
      self.proposedExcludeExportRanges = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .producerVpcSpokes) {
      self.producerVpcSpokes = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.uri, forKey: .uri)
    try container.encode(self.excludeExportRanges, forKey: .excludeExportRanges)
    try container.encode(self.includeExportRanges, forKey: .includeExportRanges)
    try container.encode(self.proposedIncludeExportRanges, forKey: .proposedIncludeExportRanges)
    try container.encode(self.proposedExcludeExportRanges, forKey: .proposedExcludeExportRanges)
    try container.encode(self.producerVpcSpokes, forKey: .producerVpcSpokes)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `LinkedVpcNetwork`: `"type.googleapis.com/google.cloud.networkconnectivity.v1.LinkedVpcNetwork"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.LinkedVpcNetwork"
  }

  /// Initialize an instance of `LinkedVpcNetwork` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.networkconnectivity.v1.LinkedVpcNetwork"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `LinkedVpcNetwork` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
