// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A collection of router appliance instances. If you configure multiple router
/// appliance instances to receive data from the same set of sites outside of
/// Google Cloud, we recommend that you associate those instances with the same
/// spoke.
public struct LinkedRouterApplianceInstances: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The list of router appliance instances.
  public var instances: [RouterApplianceInstance] = []

  /// A value that controls whether site-to-site data transfer is enabled for
  /// these resources. Data transfer is available only in [supported
  /// locations](https://cloud.google.com/network-connectivity/docs/network-connectivity-center/concepts/locations).
  public var siteToSiteDataTransfer: Swift.Bool = Swift.Bool()

  /// Output only. The VPC network where these router appliance instances are
  /// located.
  public var vpcNetwork: Swift.String = Swift.String()

  /// Optional. IP ranges allowed to be included during import from hub (does not
  /// control transit connectivity). The only allowed value for now is
  /// "ALL_IPV4_RANGES".
  public var includeImportRanges: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LinkedRouterApplianceInstances`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LinkedRouterApplianceInstances().with { $0.instances = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let instances = CodingKeys(stringValue: "instances")
    static let siteToSiteDataTransfer = CodingKeys(stringValue: "siteToSiteDataTransfer")
    static let vpcNetwork = CodingKeys(stringValue: "vpcNetwork")
    static let includeImportRanges = CodingKeys(stringValue: "includeImportRanges")

    static let _knownKeys: Set<Swift.String> = [
      "instances",
      "siteToSiteDataTransfer",
      "vpcNetwork",
      "includeImportRanges",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([RouterApplianceInstance].self, forKey: .instances)
    {
      self.instances = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .siteToSiteDataTransfer) {
      self.siteToSiteDataTransfer = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vpcNetwork) {
      self.vpcNetwork = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .includeImportRanges)
    {
      self.includeImportRanges = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.instances, forKey: .instances)
    try container.encode(self.siteToSiteDataTransfer, forKey: .siteToSiteDataTransfer)
    try container.encode(self.vpcNetwork, forKey: .vpcNetwork)
    try container.encode(self.includeImportRanges, forKey: .includeImportRanges)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `LinkedRouterApplianceInstances`: `"type.googleapis.com/google.cloud.networkconnectivity.v1.LinkedRouterApplianceInstances"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.LinkedRouterApplianceInstances"
  }

  /// Initialize an instance of `LinkedRouterApplianceInstances` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.networkconnectivity.v1.LinkedRouterApplianceInstances"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `LinkedRouterApplianceInstances` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
