// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The `MulticloudDataTransferConfig` resource. It lists the services that you
/// configure for Data Transfer Essentials billing and metering.
public struct MulticloudDataTransferConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the `MulticloudDataTransferConfig` resource.
  /// Format:
  /// `projects/{project}/locations/{location}/multicloudDataTransferConfigs/{multicloud_data_transfer_config}`.
  public var name: Swift.String = Swift.String()

  /// Output only. Time when the `MulticloudDataTransferConfig` resource was
  /// created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Time when the `MulticloudDataTransferConfig` resource was
  /// updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. User-defined labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// The etag is computed by the server, and might be sent with update and
  /// delete requests so that the client has an up-to-date value before
  /// proceeding.
  public var etag: Swift.String = Swift.String()

  /// Optional. A description of this resource.
  public var description: Swift.String = Swift.String()

  /// Output only. The number of `Destination` resources configured for the
  /// `MulticloudDataTransferConfig` resource.
  public var destinationsCount: Swift.Int32 = Swift.Int32()

  /// Output only. The number of `Destination` resources in use with the
  /// `MulticloudDataTransferConfig` resource.
  public var destinationsActiveCount: Swift.Int32 = Swift.Int32()

  /// Optional. Maps services to their current or planned states. Service names
  /// are keys, and the associated values describe the state of the service. If a
  /// state change is expected, the value is either `ADDING` or `DELETING`,
  /// depending on the actions taken.
  ///
  /// Sample output:
  /// "services": {
  ///   "big-query": {
  ///     "states": [
  ///       {
  ///         "effectiveTime": "2024-12-12T08:00:00Z"
  ///         "state": "ADDING",
  ///       },
  ///     ]
  ///   },
  ///   "cloud-storage": {
  ///     "states": [
  ///       {
  ///         "state": "ACTIVE",
  ///       }
  ///     ]
  ///   }
  /// }
  public var services: [Swift.String: StateTimeline] = [:]

  /// Output only. The Google-generated unique ID for the
  /// `MulticloudDataTransferConfig` resource. This value is unique across all
  /// `MulticloudDataTransferConfig` resources. If a resource is deleted and
  /// another with the same name is created, the new resource is assigned a
  /// different and unique ID.
  public var uid: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MulticloudDataTransferConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MulticloudDataTransferConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let etag = CodingKeys(stringValue: "etag")
    static let description = CodingKeys(stringValue: "description")
    static let destinationsCount = CodingKeys(stringValue: "destinationsCount")
    static let destinationsActiveCount = CodingKeys(stringValue: "destinationsActiveCount")
    static let services = CodingKeys(stringValue: "services")
    static let uid = CodingKeys(stringValue: "uid")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "etag",
      "description",
      "destinationsCount",
      "destinationsActiveCount",
      "services",
      "uid",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .destinationsCount) {
      self.destinationsCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .destinationsActiveCount)
    {
      self.destinationsActiveCount = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: StateTimeline].self, forKey: .services)
    {
      self.services = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.destinationsCount, forKey: .destinationsCount)
    try container.encode(self.destinationsActiveCount, forKey: .destinationsActiveCount)
    try container.encode(self.services, forKey: .services)
    try container.encode(self.uid, forKey: .uid)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.MulticloudDataTransferConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
