// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Policy-based routes route L4 network traffic based on not just destination IP
/// address, but also source IP address, protocol, and more. If a policy-based
/// route conflicts with other types of routes, the policy-based route always
/// takes precedence.
public struct PolicyBasedRoute: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Immutable. A unique name of the resource in the form of
  /// `projects/{project_number}/locations/global/PolicyBasedRoutes/{policy_based_route_id}`
  public var name: Swift.String = Swift.String()

  /// Output only. Time when the policy-based route was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Time when the policy-based route was updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// User-defined labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. An optional description of this resource. Provide this field when
  /// you create the resource.
  public var description: Swift.String = Swift.String()

  /// Required. Fully-qualified URL of the network that this route applies to,
  /// for example: projects/my-project/global/networks/my-network.
  public var network: Swift.String = Swift.String()

  /// Required. The filter to match L4 traffic.
  public var filter: PolicyBasedRoute.Filter? = nil

  /// Optional. The priority of this policy-based route. Priority is used to
  /// break ties in cases where there are more than one matching policy-based
  /// routes found. In cases where multiple policy-based routes are matched, the
  /// one with the lowest-numbered priority value wins. The default value is
  /// 1000. The priority value must be from 1 to 65535, inclusive.
  public var priority: Swift.Int32 = Swift.Int32()

  /// Output only. If potential misconfigurations are detected for this route,
  /// this field will be populated with warning messages.
  public var warnings: [PolicyBasedRoute.Warnings] = []

  /// Output only. Server-defined fully-qualified URL for this resource.
  public var selfLink: Swift.String = Swift.String()

  /// Output only. Type of this resource. Always
  /// networkconnectivity#policyBasedRoute for policy-based Route resources.
  public var kind: Swift.String = Swift.String()

  /// Target specifies network endpoints that this policy-based route applies to.
  /// If no target is specified, the PBR will be installed on all network
  /// endpoints (e.g. VMs, VPNs, and Interconnects) in the VPC.
  public var target: TargetOneOf? = nil

  public var nextHop: NextHopOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PolicyBasedRoute`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PolicyBasedRoute().with { $0.virtualMachine = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let virtualMachine = CodingKeys(stringValue: "virtualMachine")
    static let interconnectAttachment = CodingKeys(stringValue: "interconnectAttachment")
    static let nextHopIlbIp = CodingKeys(stringValue: "nextHopIlbIp")
    static let nextHopOtherRoutes = CodingKeys(stringValue: "nextHopOtherRoutes")
    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let description = CodingKeys(stringValue: "description")
    static let network = CodingKeys(stringValue: "network")
    static let filter = CodingKeys(stringValue: "filter")
    static let priority = CodingKeys(stringValue: "priority")
    static let warnings = CodingKeys(stringValue: "warnings")
    static let selfLink = CodingKeys(stringValue: "selfLink")
    static let kind = CodingKeys(stringValue: "kind")

    static let _knownKeys: Set<Swift.String> = [
      "virtualMachine",
      "interconnectAttachment",
      "nextHopIlbIp",
      "nextHopOtherRoutes",
      "name",
      "createTime",
      "updateTime",
      "labels",
      "description",
      "network",
      "filter",
      "priority",
      "warnings",
      "selfLink",
      "kind",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
      self.network = value
    }
    self.filter = try container.decodeIfPresent(PolicyBasedRoute.Filter.self, forKey: .filter)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .priority) {
      self.priority = value
    }
    if let value = try container.decodeIfPresent(
      [PolicyBasedRoute.Warnings].self, forKey: .warnings)
    {
      self.warnings = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .selfLink) {
      self.selfLink = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kind) {
      self.kind = value
    }

    var target: TargetOneOf? = nil
    let targetCheckAndSet = {
      if target != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'target'"))
      }
      target = $0
    }
    if let virtualMachine = try container.decodeIfPresent(
      PolicyBasedRoute.VirtualMachine.self, forKey: .virtualMachine)
    {
      try targetCheckAndSet(.virtualMachine(virtualMachine))
    }
    if let interconnectAttachment = try container.decodeIfPresent(
      PolicyBasedRoute.InterconnectAttachment.self, forKey: .interconnectAttachment)
    {
      try targetCheckAndSet(.interconnectAttachment(interconnectAttachment))
    }
    self.target = target

    var nextHop: NextHopOneOf? = nil
    let nextHopCheckAndSet = {
      if nextHop != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'nextHop'"))
      }
      nextHop = $0
    }
    if let nextHopIlbIp = try container.decodeIfPresent(Swift.String.self, forKey: .nextHopIlbIp) {
      try nextHopCheckAndSet(.nextHopIlbIp(nextHopIlbIp))
    }
    if let nextHopOtherRoutes = try container.decodeIfPresent(
      PolicyBasedRoute.OtherRoutes.self, forKey: .nextHopOtherRoutes)
    {
      try nextHopCheckAndSet(.nextHopOtherRoutes(nextHopOtherRoutes))
    }
    self.nextHop = nextHop
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.network, forKey: .network)
    try container.encodeIfPresent(self.filter, forKey: .filter)
    try container.encode(self.priority, forKey: .priority)
    try container.encode(self.warnings, forKey: .warnings)
    try container.encode(self.selfLink, forKey: .selfLink)
    try container.encode(self.kind, forKey: .kind)

    if let choice = self.target {
      switch choice {
      case .virtualMachine(let value):
        try container.encode(value, forKey: .virtualMachine)
      case .interconnectAttachment(let value):
        try container.encode(value, forKey: .interconnectAttachment)
      }
    }

    if let choice = self.nextHop {
      switch choice {
      case .nextHopIlbIp(let value):
        try container.encode(value, forKey: .nextHopIlbIp)
      case .nextHopOtherRoutes(let value):
        try container.encode(value, forKey: .nextHopOtherRoutes)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// VM instances that this policy-based route applies to.
  public struct VirtualMachine: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. A list of VM instance tags that this policy-based route applies
    /// to. VM instances that have ANY of tags specified here installs this PBR.
    public var tags: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `VirtualMachine`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = VirtualMachine().with { $0.tags = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let tags = CodingKeys(stringValue: "tags")

      static let _knownKeys: Set<Swift.String> = [
        "tags"
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .tags) {
        self.tags = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.tags, forKey: .tags)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `VirtualMachine`: `"type.googleapis.com/google.cloud.networkconnectivity.v1.PolicyBasedRoute.VirtualMachine"`.
    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.networkconnectivity.v1.PolicyBasedRoute.VirtualMachine"
    }

    /// Initialize an instance of `VirtualMachine` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.networkconnectivity.v1.PolicyBasedRoute.VirtualMachine"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `VirtualMachine` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// InterconnectAttachment that this route applies to.
  public struct InterconnectAttachment: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Cloud region to install this policy-based route on interconnect
    /// attachment. Use `all` to install it on all interconnect attachments.
    public var region: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `InterconnectAttachment`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InterconnectAttachment().with { $0.region = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let region = CodingKeys(stringValue: "region")

      static let _knownKeys: Set<Swift.String> = [
        "region"
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .region) {
        self.region = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.region, forKey: .region)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `InterconnectAttachment`: `"type.googleapis.com/google.cloud.networkconnectivity.v1.PolicyBasedRoute.InterconnectAttachment"`.
    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.networkconnectivity.v1.PolicyBasedRoute.InterconnectAttachment"
    }

    /// Initialize an instance of `InterconnectAttachment` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.networkconnectivity.v1.PolicyBasedRoute.InterconnectAttachment"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `InterconnectAttachment` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Filter matches L4 traffic.
  public struct Filter: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The IP protocol that this policy-based route applies to. Valid
    /// values are 'TCP', 'UDP', and 'ALL'. Default is 'ALL'.
    public var ipProtocol: Swift.String = Swift.String()

    /// Optional. The source IP range of outgoing packets that this policy-based
    /// route applies to. Default is "0.0.0.0/0" if protocol version is IPv4.
    public var srcRange: Swift.String = Swift.String()

    /// Optional. The destination IP range of outgoing packets that this
    /// policy-based route applies to. Default is "0.0.0.0/0" if protocol version
    /// is IPv4.
    public var destRange: Swift.String = Swift.String()

    /// Required. Internet protocol versions this policy-based route applies to.
    /// For this version, only IPV4 is supported. IPV6 is supported in preview.
    public var protocolVersion: PolicyBasedRoute.Filter.ProtocolVersion = PolicyBasedRoute.Filter
      .ProtocolVersion()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Filter`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Filter().with { $0.ipProtocol = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let ipProtocol = CodingKeys(stringValue: "ipProtocol")
      static let srcRange = CodingKeys(stringValue: "srcRange")
      static let destRange = CodingKeys(stringValue: "destRange")
      static let protocolVersion = CodingKeys(stringValue: "protocolVersion")

      static let _knownKeys: Set<Swift.String> = [
        "ipProtocol",
        "srcRange",
        "destRange",
        "protocolVersion",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ipProtocol) {
        self.ipProtocol = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .srcRange) {
        self.srcRange = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .destRange) {
        self.destRange = value
      }
      if let value = try container.decodeIfPresent(
        PolicyBasedRoute.Filter.ProtocolVersion.self, forKey: .protocolVersion)
      {
        self.protocolVersion = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.ipProtocol, forKey: .ipProtocol)
      try container.encode(self.srcRange, forKey: .srcRange)
      try container.encode(self.destRange, forKey: .destRange)
      try container.encode(self.protocolVersion, forKey: .protocolVersion)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The internet protocol version.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum ProtocolVersion: Codable, Equatable, Hashable, Sendable {
      /// Default value.
      case unspecified
      /// The PBR is for IPv4 internet protocol traffic.
      case ipv4
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .ipv4: return 1
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "PROTOCOL_VERSION_UNSPECIFIED"
        case .ipv4: return "IPV4"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ProtocolVersion/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "PROTOCOL_VERSION_UNSPECIFIED": self = .unspecified
        case "IPV4": self = .ipv4
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ProtocolVersion/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .ipv4
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("PROTOCOL_VERSION_UNSPECIFIED")
        case .ipv4: return try container.encode("IPV4")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The type URL for `Filter`: `"type.googleapis.com/google.cloud.networkconnectivity.v1.PolicyBasedRoute.Filter"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.networkconnectivity.v1.PolicyBasedRoute.Filter"
    }

    /// Initialize an instance of `Filter` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.networkconnectivity.v1.PolicyBasedRoute.Filter"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `Filter` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Informational warning message.
  public struct Warnings: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. A warning code, if applicable.
    public var code: PolicyBasedRoute.Warnings.Code = PolicyBasedRoute.Warnings.Code()

    /// Output only. Metadata about this warning in key: value format. The key
    /// should provides more detail on the warning being returned. For example,
    /// for warnings where there are no results in a list request for a
    /// particular zone, this key might be scope and the key value might be the
    /// zone name. Other examples might be a key indicating a deprecated resource
    /// and a suggested replacement.
    public var data: [Swift.String: Swift.String] = [:]

    /// Output only. A human-readable description of the warning code.
    public var warningMessage: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Warnings`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Warnings().with { $0.code = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let code = CodingKeys(stringValue: "code")
      static let data = CodingKeys(stringValue: "data")
      static let warningMessage = CodingKeys(stringValue: "warningMessage")

      static let _knownKeys: Set<Swift.String> = [
        "code",
        "data",
        "warningMessage",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        PolicyBasedRoute.Warnings.Code.self, forKey: .code)
      {
        self.code = value
      }
      if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .data)
      {
        self.data = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .warningMessage) {
        self.warningMessage = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.code, forKey: .code)
      try container.encode(self.data, forKey: .data)
      try container.encode(self.warningMessage, forKey: .warningMessage)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Warning code for policy-based routing. Expect to add values in the
    /// future.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum Code: Codable, Equatable, Hashable, Sendable {
      /// Default value.
      case warningUnspecified
      /// The policy-based route is not active and functioning. Common causes are
      /// that the dependent network was deleted or the resource project was
      /// turned off.
      case resourceNotActive
      /// The policy-based route is being modified (e.g. created/deleted) at this
      /// time.
      case resourceBeingModified
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .warningUnspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .warningUnspecified: return 0
        case .resourceNotActive: return 1
        case .resourceBeingModified: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .warningUnspecified: return "WARNING_UNSPECIFIED"
        case .resourceNotActive: return "RESOURCE_NOT_ACTIVE"
        case .resourceBeingModified: return "RESOURCE_BEING_MODIFIED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Code/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "WARNING_UNSPECIFIED": self = .warningUnspecified
        case "RESOURCE_NOT_ACTIVE": self = .resourceNotActive
        case "RESOURCE_BEING_MODIFIED": self = .resourceBeingModified
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Code/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .warningUnspecified
        case 1: self = .resourceNotActive
        case 2: self = .resourceBeingModified
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .warningUnspecified: return try container.encode("WARNING_UNSPECIFIED")
        case .resourceNotActive: return try container.encode("RESOURCE_NOT_ACTIVE")
        case .resourceBeingModified: return try container.encode("RESOURCE_BEING_MODIFIED")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The type URL for `Warnings`: `"type.googleapis.com/google.cloud.networkconnectivity.v1.PolicyBasedRoute.Warnings"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.networkconnectivity.v1.PolicyBasedRoute.Warnings"
    }

    /// Initialize an instance of `Warnings` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.networkconnectivity.v1.PolicyBasedRoute.Warnings"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `Warnings` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The other routing cases.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum OtherRoutes: Codable, Equatable, Hashable, Sendable {
    /// Default value.
    case unspecified
    /// Use the routes from the default routing tables (system-generated routes,
    /// custom routes, peering route) to determine the next hop. This effectively
    /// excludes matching packets being applied on other PBRs with a lower
    /// priority.
    case defaultRouting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .defaultRouting: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "OTHER_ROUTES_UNSPECIFIED"
      case .defaultRouting: return "DEFAULT_ROUTING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:OtherRoutes/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "OTHER_ROUTES_UNSPECIFIED": self = .unspecified
      case "DEFAULT_ROUTING": self = .defaultRouting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:OtherRoutes/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .defaultRouting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("OTHER_ROUTES_UNSPECIFIED")
      case .defaultRouting: return try container.encode("DEFAULT_ROUTING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Target specifies network endpoints that this policy-based route applies to.
  /// If no target is specified, the PBR will be installed on all network
  /// endpoints (e.g. VMs, VPNs, and Interconnects) in the VPC.
  public enum TargetOneOf: Codable, Equatable, Sendable {
    /// Optional. VM instances that this policy-based route applies to.
    indirect case virtualMachine(PolicyBasedRoute.VirtualMachine)
    /// Optional. The interconnect attachments that this policy-based route
    /// applies to.
    indirect case interconnectAttachment(PolicyBasedRoute.InterconnectAttachment)
  }

  public enum NextHopOneOf: Codable, Equatable, Sendable {
    /// Optional. The IP address of a global-access-enabled L4 ILB that is the
    /// next hop for matching packets. For this version, only nextHopIlbIp is
    /// supported.
    case nextHopIlbIp(Swift.String)
    /// Optional. Other routes that will be referenced to determine the next hop
    /// of the packet.
    case nextHopOtherRoutes(PolicyBasedRoute.OtherRoutes)
  }

  /// The type URL for `PolicyBasedRoute`: `"type.googleapis.com/google.cloud.networkconnectivity.v1.PolicyBasedRoute"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.PolicyBasedRoute"
  }

  /// Initialize an instance of `PolicyBasedRoute` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.networkconnectivity.v1.PolicyBasedRoute"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `PolicyBasedRoute` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
