// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The ServiceConnectionMap resource.
public struct ServiceConnectionMap: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Immutable. The name of a ServiceConnectionMap.
  /// Format:
  /// projects/{project}/locations/{location}/serviceConnectionMaps/{service_connection_map}
  /// See: https://google.aip.dev/122#fields-representing-resource-names
  public var name: Swift.String = Swift.String()

  /// Output only. Time when the ServiceConnectionMap was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Time when the ServiceConnectionMap was updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// User-defined labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// A description of this resource.
  public var description: Swift.String = Swift.String()

  /// The service class identifier this ServiceConnectionMap is for.
  /// The user of ServiceConnectionMap create API needs to have
  /// networkconnecitivty.serviceclasses.use iam permission for the service
  /// class.
  public var serviceClass: Swift.String = Swift.String()

  /// Output only. The service class uri this ServiceConnectionMap is for.
  public var serviceClassUri: Swift.String = Swift.String()

  /// Output only. The infrastructure used for connections between
  /// consumers/producers.
  public var infrastructure: Infrastructure = Infrastructure()

  /// The PSC configurations on producer side.
  public var producerPscConfigs: [ServiceConnectionMap.ProducerPscConfig] = []

  /// The PSC configurations on consumer side.
  public var consumerPscConfigs: [ServiceConnectionMap.ConsumerPscConfig] = []

  /// Output only. PSC connection details on consumer side.
  public var consumerPscConnections: [ServiceConnectionMap.ConsumerPscConnection] = []

  /// The token provided by the consumer. This token authenticates that the
  /// consumer can create a connection within the specified project and network.
  public var token: Swift.String = Swift.String()

  /// Optional. The etag is computed by the server, and may be sent on update and
  /// delete requests to ensure the client has an up-to-date value before
  /// proceeding.
  public var etag: Swift.String? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ServiceConnectionMap`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ServiceConnectionMap().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let description = CodingKeys(stringValue: "description")
    static let serviceClass = CodingKeys(stringValue: "serviceClass")
    static let serviceClassUri = CodingKeys(stringValue: "serviceClassUri")
    static let infrastructure = CodingKeys(stringValue: "infrastructure")
    static let producerPscConfigs = CodingKeys(stringValue: "producerPscConfigs")
    static let consumerPscConfigs = CodingKeys(stringValue: "consumerPscConfigs")
    static let consumerPscConnections = CodingKeys(stringValue: "consumerPscConnections")
    static let token = CodingKeys(stringValue: "token")
    static let etag = CodingKeys(stringValue: "etag")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "description",
      "serviceClass",
      "serviceClassUri",
      "infrastructure",
      "producerPscConfigs",
      "consumerPscConfigs",
      "consumerPscConnections",
      "token",
      "etag",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceClass) {
      self.serviceClass = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceClassUri) {
      self.serviceClassUri = value
    }
    if let value = try container.decodeIfPresent(Infrastructure.self, forKey: .infrastructure) {
      self.infrastructure = value
    }
    if let value = try container.decodeIfPresent(
      [ServiceConnectionMap.ProducerPscConfig].self, forKey: .producerPscConfigs)
    {
      self.producerPscConfigs = value
    }
    if let value = try container.decodeIfPresent(
      [ServiceConnectionMap.ConsumerPscConfig].self, forKey: .consumerPscConfigs)
    {
      self.consumerPscConfigs = value
    }
    if let value = try container.decodeIfPresent(
      [ServiceConnectionMap.ConsumerPscConnection].self, forKey: .consumerPscConnections)
    {
      self.consumerPscConnections = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .token) {
      self.token = value
    }
    self.etag = try container.decodeIfPresent(Swift.String.self, forKey: .etag)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.serviceClass, forKey: .serviceClass)
    try container.encode(self.serviceClassUri, forKey: .serviceClassUri)
    try container.encode(self.infrastructure, forKey: .infrastructure)
    try container.encode(self.producerPscConfigs, forKey: .producerPscConfigs)
    try container.encode(self.consumerPscConfigs, forKey: .consumerPscConfigs)
    try container.encode(self.consumerPscConnections, forKey: .consumerPscConnections)
    try container.encode(self.token, forKey: .token)
    try container.encodeIfPresent(self.etag, forKey: .etag)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The PSC configurations on producer side.
  public struct ProducerPscConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The resource path of a service attachment.
    /// Example:
    /// projects/{projectNumOrId}/regions/{region}/serviceAttachments/{resourceId}.
    public var serviceAttachmentUri: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ProducerPscConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ProducerPscConfig().with { $0.serviceAttachmentUri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let serviceAttachmentUri = CodingKeys(stringValue: "serviceAttachmentUri")

      static let _knownKeys: Set<Swift.String> = [
        "serviceAttachmentUri"
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAttachmentUri)
      {
        self.serviceAttachmentUri = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.serviceAttachmentUri, forKey: .serviceAttachmentUri)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `ProducerPscConfig`: `"type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceConnectionMap.ProducerPscConfig"`.
    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceConnectionMap.ProducerPscConfig"
    }

    /// Initialize an instance of `ProducerPscConfig` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceConnectionMap.ProducerPscConfig"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `ProducerPscConfig` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Allow the producer to specify which consumers can connect to it.
  public struct ConsumerPscConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The consumer project where PSC connections are allowed to be created in.
    public var project: Swift.String = Swift.String()

    /// The resource path of the consumer network where PSC connections are
    /// allowed to be created in. Note, this network does not need be in the
    /// ConsumerPscConfig.project in the case of SharedVPC.
    /// Example:
    /// projects/{projectNumOrId}/global/networks/{networkId}.
    public var network: Swift.String = Swift.String()

    /// This is used in PSC consumer ForwardingRule to control whether the PSC
    /// endpoint can be accessed from another region.
    public var disableGlobalAccess: Swift.Bool = Swift.Bool()

    /// Output only. Overall state of PSC Connections management for this
    /// consumer psc config.
    public var state: ServiceConnectionMap.ConsumerPscConfig.State = ServiceConnectionMap
      .ConsumerPscConfig.State()

    /// Immutable. Deprecated. Use producer_instance_metadata instead.
    /// An immutable identifier for the producer instance.
    @available(*, deprecated)
    public var producerInstanceId: Swift.String = Swift.String()

    /// Output only. A map to store mapping between customer vip and target
    /// service attachment. Only service attachment with producer specified ip
    /// addresses are stored here.
    public var serviceAttachmentIpAddressMap: [Swift.String: Swift.String] = [:]

    /// Required. The project ID or project number of the consumer project. This
    /// project is the one that the consumer uses to interact with the producer
    /// instance. From the perspective of a consumer who's created a producer
    /// instance, this is the project of the producer instance. Format:
    /// 'projects/<project_id_or_number>' Eg. 'projects/consumer-project' or
    /// 'projects/1234'
    public var consumerInstanceProject: Swift.String = Swift.String()

    /// Immutable. An immutable map for the producer instance metadata.
    public var producerInstanceMetadata: [Swift.String: Swift.String] = [:]

    /// The requested IP version for the PSC connection.
    public var ipVersion: IPVersion? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ConsumerPscConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConsumerPscConfig().with { $0.project = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let project = CodingKeys(stringValue: "project")
      static let network = CodingKeys(stringValue: "network")
      static let disableGlobalAccess = CodingKeys(stringValue: "disableGlobalAccess")
      static let state = CodingKeys(stringValue: "state")
      static let producerInstanceId = CodingKeys(stringValue: "producerInstanceId")
      static let serviceAttachmentIpAddressMap = CodingKeys(
        stringValue: "serviceAttachmentIpAddressMap")
      static let consumerInstanceProject = CodingKeys(stringValue: "consumerInstanceProject")
      static let producerInstanceMetadata = CodingKeys(stringValue: "producerInstanceMetadata")
      static let ipVersion = CodingKeys(stringValue: "ipVersion")

      static let _knownKeys: Set<Swift.String> = [
        "project",
        "network",
        "disableGlobalAccess",
        "state",
        "producerInstanceId",
        "serviceAttachmentIpAddressMap",
        "consumerInstanceProject",
        "producerInstanceMetadata",
        "ipVersion",
      ]
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
        self.network = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disableGlobalAccess) {
        self.disableGlobalAccess = value
      }
      if let value = try container.decodeIfPresent(
        ServiceConnectionMap.ConsumerPscConfig.State.self, forKey: .state)
      {
        self.state = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .producerInstanceId) {
        self.producerInstanceId = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .serviceAttachmentIpAddressMap)
      {
        self.serviceAttachmentIpAddressMap = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .consumerInstanceProject)
      {
        self.consumerInstanceProject = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .producerInstanceMetadata)
      {
        self.producerInstanceMetadata = value
      }
      self.ipVersion = try container.decodeIfPresent(IPVersion.self, forKey: .ipVersion)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.project, forKey: .project)
      try container.encode(self.network, forKey: .network)
      try container.encode(self.disableGlobalAccess, forKey: .disableGlobalAccess)
      try container.encode(self.state, forKey: .state)
      try container.encode(self.producerInstanceId, forKey: .producerInstanceId)
      try container.encode(
        self.serviceAttachmentIpAddressMap, forKey: .serviceAttachmentIpAddressMap)
      try container.encode(self.consumerInstanceProject, forKey: .consumerInstanceProject)
      try container.encode(self.producerInstanceMetadata, forKey: .producerInstanceMetadata)
      try container.encodeIfPresent(self.ipVersion, forKey: .ipVersion)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// PSC Consumer Config State.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum State: Codable, Equatable, Hashable, Sendable {
      /// Default state, when Connection Map is created initially.
      case unspecified
      /// Set when policy and map configuration is valid,
      /// and their matching can lead to allowing creation of PSC Connections
      /// subject to other constraints like connections limit.
      case valid
      /// No Service Connection Policy found for this network and Service
      /// Class
      case connectionPolicyMissing
      /// Service Connection Policy limit reached for this network and Service
      /// Class
      case policyLimitReached
      /// The consumer instance project is not in
      /// AllowedGoogleProducersResourceHierarchyLevels of the matching
      /// ServiceConnectionPolicy.
      case consumerInstanceProjectNotAllowlisted
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .valid: return 1
        case .connectionPolicyMissing: return 2
        case .policyLimitReached: return 3
        case .consumerInstanceProjectNotAllowlisted: return 4
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "STATE_UNSPECIFIED"
        case .valid: return "VALID"
        case .connectionPolicyMissing: return "CONNECTION_POLICY_MISSING"
        case .policyLimitReached: return "POLICY_LIMIT_REACHED"
        case .consumerInstanceProjectNotAllowlisted:
          return "CONSUMER_INSTANCE_PROJECT_NOT_ALLOWLISTED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "STATE_UNSPECIFIED": self = .unspecified
        case "VALID": self = .valid
        case "CONNECTION_POLICY_MISSING": self = .connectionPolicyMissing
        case "POLICY_LIMIT_REACHED": self = .policyLimitReached
        case "CONSUMER_INSTANCE_PROJECT_NOT_ALLOWLISTED":
          self = .consumerInstanceProjectNotAllowlisted
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .valid
        case 2: self = .connectionPolicyMissing
        case 3: self = .policyLimitReached
        case 4: self = .consumerInstanceProjectNotAllowlisted
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("STATE_UNSPECIFIED")
        case .valid: return try container.encode("VALID")
        case .connectionPolicyMissing: return try container.encode("CONNECTION_POLICY_MISSING")
        case .policyLimitReached: return try container.encode("POLICY_LIMIT_REACHED")
        case .consumerInstanceProjectNotAllowlisted:
          return try container.encode("CONSUMER_INSTANCE_PROJECT_NOT_ALLOWLISTED")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The type URL for `ConsumerPscConfig`: `"type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceConnectionMap.ConsumerPscConfig"`.
    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceConnectionMap.ConsumerPscConfig"
    }

    /// Initialize an instance of `ConsumerPscConfig` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceConnectionMap.ConsumerPscConfig"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `ConsumerPscConfig` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// PSC connection details on consumer side.
  public struct ConsumerPscConnection: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The URI of a service attachment which is the target of the PSC
    /// connection.
    public var serviceAttachmentUri: Swift.String = Swift.String()

    /// The state of the PSC connection.
    public var state: ServiceConnectionMap.ConsumerPscConnection.State = ServiceConnectionMap
      .ConsumerPscConnection.State()

    /// The consumer project whose PSC forwarding rule is connected to the
    /// service attachments in this service connection map.
    public var project: Swift.String = Swift.String()

    /// The consumer network whose PSC forwarding rule is connected to the
    /// service attachments in this service connection map.
    /// Note that the network could be on a different project (shared VPC).
    public var network: Swift.String = Swift.String()

    /// The PSC connection id of the PSC forwarding rule connected
    /// to the service attachments in this service connection map.
    public var pscConnectionId: Swift.String = Swift.String()

    /// The IP literal allocated on the consumer network for the PSC forwarding
    /// rule that is created to connect to the producer service attachment in
    /// this service connection map.
    public var ip: Swift.String = Swift.String()

    /// The error type indicates whether the error is consumer facing, producer
    /// facing or system internal.
    @available(*, deprecated)
    public var errorType: ConnectionErrorType = ConnectionErrorType()

    /// The most recent error during operating this connection.
    @available(*, deprecated)
    public var error: GoogleRpc.Status? = nil

    /// The last Compute Engine operation to setup PSC connection.
    public var gceOperation: Swift.String = Swift.String()

    /// The URI of the consumer forwarding rule created.
    /// Example:
    /// projects/{projectNumOrId}/regions/us-east1/networks/{resourceId}.
    public var forwardingRule: Swift.String = Swift.String()

    /// Output only. The error info for the latest error during operating this
    /// connection.
    public var errorInfo: GoogleRpc.ErrorInfo? = nil

    /// Output only. The URI of the selected subnetwork selected to allocate IP
    /// address for this connection.
    public var selectedSubnetwork: Swift.String = Swift.String()

    /// Immutable. Deprecated. Use producer_instance_metadata instead.
    /// An immutable identifier for the producer instance.
    @available(*, deprecated)
    public var producerInstanceId: Swift.String = Swift.String()

    /// Immutable. An immutable map for the producer instance metadata.
    public var producerInstanceMetadata: [Swift.String: Swift.String] = [:]

    /// The requested IP version for the PSC connection.
    public var ipVersion: IPVersion? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ConsumerPscConnection`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConsumerPscConnection().with { $0.serviceAttachmentUri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let serviceAttachmentUri = CodingKeys(stringValue: "serviceAttachmentUri")
      static let state = CodingKeys(stringValue: "state")
      static let project = CodingKeys(stringValue: "project")
      static let network = CodingKeys(stringValue: "network")
      static let pscConnectionId = CodingKeys(stringValue: "pscConnectionId")
      static let ip = CodingKeys(stringValue: "ip")
      static let errorType = CodingKeys(stringValue: "errorType")
      static let error = CodingKeys(stringValue: "error")
      static let gceOperation = CodingKeys(stringValue: "gceOperation")
      static let forwardingRule = CodingKeys(stringValue: "forwardingRule")
      static let errorInfo = CodingKeys(stringValue: "errorInfo")
      static let selectedSubnetwork = CodingKeys(stringValue: "selectedSubnetwork")
      static let producerInstanceId = CodingKeys(stringValue: "producerInstanceId")
      static let producerInstanceMetadata = CodingKeys(stringValue: "producerInstanceMetadata")
      static let ipVersion = CodingKeys(stringValue: "ipVersion")

      static let _knownKeys: Set<Swift.String> = [
        "serviceAttachmentUri",
        "state",
        "project",
        "network",
        "pscConnectionId",
        "ip",
        "errorType",
        "error",
        "gceOperation",
        "forwardingRule",
        "errorInfo",
        "selectedSubnetwork",
        "producerInstanceId",
        "producerInstanceMetadata",
        "ipVersion",
      ]
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAttachmentUri)
      {
        self.serviceAttachmentUri = value
      }
      if let value = try container.decodeIfPresent(
        ServiceConnectionMap.ConsumerPscConnection.State.self, forKey: .state)
      {
        self.state = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
        self.network = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pscConnectionId) {
        self.pscConnectionId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ip) {
        self.ip = value
      }
      if let value = try container.decodeIfPresent(ConnectionErrorType.self, forKey: .errorType) {
        self.errorType = value
      }
      self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gceOperation) {
        self.gceOperation = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .forwardingRule) {
        self.forwardingRule = value
      }
      self.errorInfo = try container.decodeIfPresent(GoogleRpc.ErrorInfo.self, forKey: .errorInfo)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .selectedSubnetwork) {
        self.selectedSubnetwork = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .producerInstanceId) {
        self.producerInstanceId = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .producerInstanceMetadata)
      {
        self.producerInstanceMetadata = value
      }
      self.ipVersion = try container.decodeIfPresent(IPVersion.self, forKey: .ipVersion)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.serviceAttachmentUri, forKey: .serviceAttachmentUri)
      try container.encode(self.state, forKey: .state)
      try container.encode(self.project, forKey: .project)
      try container.encode(self.network, forKey: .network)
      try container.encode(self.pscConnectionId, forKey: .pscConnectionId)
      try container.encode(self.ip, forKey: .ip)
      try container.encode(self.errorType, forKey: .errorType)
      try container.encodeIfPresent(self.error, forKey: .error)
      try container.encode(self.gceOperation, forKey: .gceOperation)
      try container.encode(self.forwardingRule, forKey: .forwardingRule)
      try container.encodeIfPresent(self.errorInfo, forKey: .errorInfo)
      try container.encode(self.selectedSubnetwork, forKey: .selectedSubnetwork)
      try container.encode(self.producerInstanceId, forKey: .producerInstanceId)
      try container.encode(self.producerInstanceMetadata, forKey: .producerInstanceMetadata)
      try container.encodeIfPresent(self.ipVersion, forKey: .ipVersion)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The state of the PSC connection.
    /// We reserve the right to add more states without notice in the future.
    /// Users should not use exhaustive switch statements on this enum.
    /// See https://google.aip.dev/216.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum State: Codable, Equatable, Hashable, Sendable {
      /// An invalid state as the default case.
      case unspecified
      /// The connection has been created successfully. However, for the
      /// up-to-date connection status, please use the service attachment's
      /// "ConnectedEndpoint.status" as the source of truth.
      case active
      /// The connection is not functional since some resources on the connection
      /// fail to be created.
      case failed
      /// The connection is being created.
      case creating
      /// The connection is being deleted.
      case deleting
      /// The connection is being repaired to complete creation.
      case createRepairing
      /// The connection is being repaired to complete deletion.
      case deleteRepairing
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .active: return 1
        case .failed: return 2
        case .creating: return 3
        case .deleting: return 4
        case .createRepairing: return 5
        case .deleteRepairing: return 6
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "STATE_UNSPECIFIED"
        case .active: return "ACTIVE"
        case .failed: return "FAILED"
        case .creating: return "CREATING"
        case .deleting: return "DELETING"
        case .createRepairing: return "CREATE_REPAIRING"
        case .deleteRepairing: return "DELETE_REPAIRING"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "STATE_UNSPECIFIED": self = .unspecified
        case "ACTIVE": self = .active
        case "FAILED": self = .failed
        case "CREATING": self = .creating
        case "DELETING": self = .deleting
        case "CREATE_REPAIRING": self = .createRepairing
        case "DELETE_REPAIRING": self = .deleteRepairing
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .active
        case 2: self = .failed
        case 3: self = .creating
        case 4: self = .deleting
        case 5: self = .createRepairing
        case 6: self = .deleteRepairing
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("STATE_UNSPECIFIED")
        case .active: return try container.encode("ACTIVE")
        case .failed: return try container.encode("FAILED")
        case .creating: return try container.encode("CREATING")
        case .deleting: return try container.encode("DELETING")
        case .createRepairing: return try container.encode("CREATE_REPAIRING")
        case .deleteRepairing: return try container.encode("DELETE_REPAIRING")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The type URL for `ConsumerPscConnection`: `"type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceConnectionMap.ConsumerPscConnection"`.
    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceConnectionMap.ConsumerPscConnection"
    }

    /// Initialize an instance of `ConsumerPscConnection` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceConnectionMap.ConsumerPscConnection"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `ConsumerPscConnection` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The type URL for `ServiceConnectionMap`: `"type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceConnectionMap"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceConnectionMap"
  }

  /// Initialize an instance of `ServiceConnectionMap` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceConnectionMap"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ServiceConnectionMap` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
