// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The ServiceConnectionPolicy resource.
public struct ServiceConnectionPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Immutable. The name of a ServiceConnectionPolicy.
  /// Format:
  /// projects/{project}/locations/{location}/serviceConnectionPolicies/{service_connection_policy}
  /// See: https://google.aip.dev/122#fields-representing-resource-names
  public var name: Swift.String = Swift.String()

  /// Output only. Time when the ServiceConnectionPolicy was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Time when the ServiceConnectionPolicy was updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// User-defined labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// A description of this resource.
  public var description: Swift.String = Swift.String()

  /// The resource path of the consumer network.
  /// Example:
  /// - projects/{projectNumOrId}/global/networks/{resourceId}.
  public var network: Swift.String = Swift.String()

  /// The service class identifier for which this ServiceConnectionPolicy is for.
  /// The service class identifier is a unique, symbolic representation of a
  /// ServiceClass. It is provided by the Service Producer. Google services have
  /// a prefix of gcp or google-cloud. For example, gcp-memorystore-redis or
  /// google-cloud-sql. 3rd party services do not. For example,
  /// test-service-a3dfcx.
  public var serviceClass: Swift.String = Swift.String()

  /// Output only. The type of underlying resources used to create the
  /// connection.
  public var infrastructure: Infrastructure = Infrastructure()

  /// Configuration used for Private Service Connect connections. Used when
  /// Infrastructure is PSC.
  public var pscConfig: ServiceConnectionPolicy.PscConfig? = nil

  /// Output only. [Output only] Information about each Private Service Connect
  /// connection.
  public var pscConnections: [ServiceConnectionPolicy.PscConnection] = []

  /// Optional. The etag is computed by the server, and may be sent on update and
  /// delete requests to ensure the client has an up-to-date value before
  /// proceeding.
  public var etag: Swift.String? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ServiceConnectionPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ServiceConnectionPolicy().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let description = CodingKeys(stringValue: "description")
    static let network = CodingKeys(stringValue: "network")
    static let serviceClass = CodingKeys(stringValue: "serviceClass")
    static let infrastructure = CodingKeys(stringValue: "infrastructure")
    static let pscConfig = CodingKeys(stringValue: "pscConfig")
    static let pscConnections = CodingKeys(stringValue: "pscConnections")
    static let etag = CodingKeys(stringValue: "etag")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "description",
      "network",
      "serviceClass",
      "infrastructure",
      "pscConfig",
      "pscConnections",
      "etag",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
      self.network = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceClass) {
      self.serviceClass = value
    }
    if let value = try container.decodeIfPresent(Infrastructure.self, forKey: .infrastructure) {
      self.infrastructure = value
    }
    self.pscConfig = try container.decodeIfPresent(
      ServiceConnectionPolicy.PscConfig.self, forKey: .pscConfig)
    if let value = try container.decodeIfPresent(
      [ServiceConnectionPolicy.PscConnection].self, forKey: .pscConnections)
    {
      self.pscConnections = value
    }
    self.etag = try container.decodeIfPresent(Swift.String.self, forKey: .etag)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.network, forKey: .network)
    try container.encode(self.serviceClass, forKey: .serviceClass)
    try container.encode(self.infrastructure, forKey: .infrastructure)
    try container.encodeIfPresent(self.pscConfig, forKey: .pscConfig)
    try container.encode(self.pscConnections, forKey: .pscConnections)
    try container.encodeIfPresent(self.etag, forKey: .etag)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Configuration used for Private Service Connect connections. Used when
  /// Infrastructure is PSC.
  public struct PscConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The resource paths of subnetworks to use for IP address management.
    /// Example:
    /// projects/{projectNumOrId}/regions/{region}/subnetworks/{resourceId}.
    public var subnetworks: [Swift.String] = []

    /// Optional. Max number of PSC connections for this policy.
    public var limit: Swift.Int64? = nil

    /// Required. ProducerInstanceLocation is used to specify which authorization
    /// mechanism to use to determine which projects the Producer instance can be
    /// within.
    public var producerInstanceLocation:
      ServiceConnectionPolicy.PscConfig.ProducerInstanceLocation = ServiceConnectionPolicy.PscConfig
        .ProducerInstanceLocation()

    /// Optional. List of Projects, Folders, or Organizations from where the
    /// Producer instance can be within. For example, a network administrator can
    /// provide both 'organizations/foo' and 'projects/bar' as
    /// allowed_google_producers_resource_hierarchy_levels. This allowlists this
    /// network to connect with any Producer instance within the 'foo'
    /// organization or the 'bar' project. By default,
    /// allowed_google_producers_resource_hierarchy_level is empty. The format
    /// for each allowed_google_producers_resource_hierarchy_level is <resource
    /// type>/<id> where <resource type> is one of 'projects', 'folders', or
    /// 'organizations' and <id> is either the ID or the number of the resource
    /// type. Format for each allowed_google_producers_resource_hierarchy_level
    /// value: 'projects/<project_id_or_number>' or 'folders/<folder_id>' or
    /// 'organizations/<organization_id>'
    /// Eg. [projects/my-project-id, projects/567, folders/891,
    /// organizations/123]
    public var allowedGoogleProducersResourceHierarchyLevel: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PscConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PscConfig().with { $0.subnetworks = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let subnetworks = CodingKeys(stringValue: "subnetworks")
      static let limit = CodingKeys(stringValue: "limit")
      static let producerInstanceLocation = CodingKeys(stringValue: "producerInstanceLocation")
      static let allowedGoogleProducersResourceHierarchyLevel = CodingKeys(
        stringValue: "allowedGoogleProducersResourceHierarchyLevel")

      static let _knownKeys: Set<Swift.String> = [
        "subnetworks",
        "limit",
        "producerInstanceLocation",
        "allowedGoogleProducersResourceHierarchyLevel",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .subnetworks) {
        self.subnetworks = value
      }
      self.limit = try container.decodeIfPresent(Swift.Int64.self, forKey: .limit)
      if let value = try container.decodeIfPresent(
        ServiceConnectionPolicy.PscConfig.ProducerInstanceLocation.self,
        forKey: .producerInstanceLocation)
      {
        self.producerInstanceLocation = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String].self, forKey: .allowedGoogleProducersResourceHierarchyLevel)
      {
        self.allowedGoogleProducersResourceHierarchyLevel = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.subnetworks, forKey: .subnetworks)
      try container.encodeIfPresent(self.limit, forKey: .limit)
      try container.encode(self.producerInstanceLocation, forKey: .producerInstanceLocation)
      try container.encode(
        self.allowedGoogleProducersResourceHierarchyLevel,
        forKey: .allowedGoogleProducersResourceHierarchyLevel)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// ProducerInstanceLocation is used to specify which authorization mechanism
    /// to use to determine which projects the Producer instance can be within.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum ProducerInstanceLocation: Codable, Equatable, Hashable, Sendable {
      /// Producer instance location is not specified. When this option is
      /// chosen, then the PSC connections created by this
      /// ServiceConnectionPolicy must be within the same project as the Producer
      /// instance. This is the default ProducerInstanceLocation value.
      /// To allow for PSC connections from this network to other networks, use
      /// the CUSTOM_RESOURCE_HIERARCHY_LEVELS option.
      case unspecified
      /// Producer instance must be within one of the values provided in
      /// allowed_google_producers_resource_hierarchy_level.
      case customResourceHierarchyLevels
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .customResourceHierarchyLevels: return 1
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "PRODUCER_INSTANCE_LOCATION_UNSPECIFIED"
        case .customResourceHierarchyLevels: return "CUSTOM_RESOURCE_HIERARCHY_LEVELS"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ProducerInstanceLocation/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "PRODUCER_INSTANCE_LOCATION_UNSPECIFIED": self = .unspecified
        case "CUSTOM_RESOURCE_HIERARCHY_LEVELS": self = .customResourceHierarchyLevels
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ProducerInstanceLocation/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .customResourceHierarchyLevels
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("PRODUCER_INSTANCE_LOCATION_UNSPECIFIED")
        case .customResourceHierarchyLevels:
          return try container.encode("CUSTOM_RESOURCE_HIERARCHY_LEVELS")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceConnectionPolicy.PscConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Information about a specific Private Service Connect connection.
  public struct PscConnection: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// State of the PSC Connection
    public var state: ServiceConnectionPolicy.State = ServiceConnectionPolicy.State()

    /// The resource reference of the PSC Forwarding Rule within the consumer
    /// VPC.
    public var consumerForwardingRule: Swift.String = Swift.String()

    /// The resource reference of the consumer address.
    public var consumerAddress: Swift.String = Swift.String()

    /// The error type indicates whether the error is consumer facing, producer
    /// facing or system internal.
    @available(*, deprecated)
    public var errorType: ConnectionErrorType = ConnectionErrorType()

    /// The most recent error during operating this connection.
    /// Deprecated, please use error_info instead.
    @available(*, deprecated)
    public var error: GoogleRpc.Status? = nil

    /// The last Compute Engine operation to setup PSC connection.
    public var gceOperation: Swift.String = Swift.String()

    /// The project where the PSC connection is created.
    public var consumerTargetProject: Swift.String = Swift.String()

    /// The PSC connection id of the PSC forwarding rule.
    public var pscConnectionId: Swift.String = Swift.String()

    /// Output only. The error info for the latest error during operating this
    /// connection.
    public var errorInfo: GoogleRpc.ErrorInfo? = nil

    /// Output only. The URI of the subnetwork selected to allocate IP address
    /// for this connection.
    public var selectedSubnetwork: Swift.String = Swift.String()

    /// Immutable. Deprecated. Use producer_instance_metadata instead.
    /// An immutable identifier for the producer instance.
    @available(*, deprecated)
    public var producerInstanceId: Swift.String = Swift.String()

    /// Immutable. An immutable map for the producer instance metadata.
    public var producerInstanceMetadata: [Swift.String: Swift.String] = [:]

    /// Output only. [Output only] The service class associated with this PSC
    /// Connection. The value is derived from the SCPolicy and matches the
    /// service class name provided by the customer.
    public var serviceClass: Swift.String = Swift.String()

    /// The requested IP version for the PSC connection.
    public var ipVersion: IPVersion? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PscConnection`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PscConnection().with { $0.state = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let state = CodingKeys(stringValue: "state")
      static let consumerForwardingRule = CodingKeys(stringValue: "consumerForwardingRule")
      static let consumerAddress = CodingKeys(stringValue: "consumerAddress")
      static let errorType = CodingKeys(stringValue: "errorType")
      static let error = CodingKeys(stringValue: "error")
      static let gceOperation = CodingKeys(stringValue: "gceOperation")
      static let consumerTargetProject = CodingKeys(stringValue: "consumerTargetProject")
      static let pscConnectionId = CodingKeys(stringValue: "pscConnectionId")
      static let errorInfo = CodingKeys(stringValue: "errorInfo")
      static let selectedSubnetwork = CodingKeys(stringValue: "selectedSubnetwork")
      static let producerInstanceId = CodingKeys(stringValue: "producerInstanceId")
      static let producerInstanceMetadata = CodingKeys(stringValue: "producerInstanceMetadata")
      static let serviceClass = CodingKeys(stringValue: "serviceClass")
      static let ipVersion = CodingKeys(stringValue: "ipVersion")

      static let _knownKeys: Set<Swift.String> = [
        "state",
        "consumerForwardingRule",
        "consumerAddress",
        "errorType",
        "error",
        "gceOperation",
        "consumerTargetProject",
        "pscConnectionId",
        "errorInfo",
        "selectedSubnetwork",
        "producerInstanceId",
        "producerInstanceMetadata",
        "serviceClass",
        "ipVersion",
      ]
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        ServiceConnectionPolicy.State.self, forKey: .state)
      {
        self.state = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .consumerForwardingRule)
      {
        self.consumerForwardingRule = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .consumerAddress) {
        self.consumerAddress = value
      }
      if let value = try container.decodeIfPresent(ConnectionErrorType.self, forKey: .errorType) {
        self.errorType = value
      }
      self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gceOperation) {
        self.gceOperation = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .consumerTargetProject)
      {
        self.consumerTargetProject = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pscConnectionId) {
        self.pscConnectionId = value
      }
      self.errorInfo = try container.decodeIfPresent(GoogleRpc.ErrorInfo.self, forKey: .errorInfo)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .selectedSubnetwork) {
        self.selectedSubnetwork = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .producerInstanceId) {
        self.producerInstanceId = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .producerInstanceMetadata)
      {
        self.producerInstanceMetadata = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceClass) {
        self.serviceClass = value
      }
      self.ipVersion = try container.decodeIfPresent(IPVersion.self, forKey: .ipVersion)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.state, forKey: .state)
      try container.encode(self.consumerForwardingRule, forKey: .consumerForwardingRule)
      try container.encode(self.consumerAddress, forKey: .consumerAddress)
      try container.encode(self.errorType, forKey: .errorType)
      try container.encodeIfPresent(self.error, forKey: .error)
      try container.encode(self.gceOperation, forKey: .gceOperation)
      try container.encode(self.consumerTargetProject, forKey: .consumerTargetProject)
      try container.encode(self.pscConnectionId, forKey: .pscConnectionId)
      try container.encodeIfPresent(self.errorInfo, forKey: .errorInfo)
      try container.encode(self.selectedSubnetwork, forKey: .selectedSubnetwork)
      try container.encode(self.producerInstanceId, forKey: .producerInstanceId)
      try container.encode(self.producerInstanceMetadata, forKey: .producerInstanceMetadata)
      try container.encode(self.serviceClass, forKey: .serviceClass)
      try container.encodeIfPresent(self.ipVersion, forKey: .ipVersion)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceConnectionPolicy.PscConnection"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The state of the PSC connection.
  /// We reserve the right to add more states without notice in the future.
  /// Users should not use exhaustive switch statements on this enum.
  /// See https://google.aip.dev/216.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// An invalid state as the default case.
    case unspecified
    /// The connection has been created successfully. However, for the
    /// up-to-date connection status, please use the created forwarding rule's
    /// "PscConnectionStatus" as the source of truth.
    case active
    /// The connection is not functional since some resources on the connection
    /// fail to be created.
    case failed
    /// The connection is being created.
    case creating
    /// The connection is being deleted.
    case deleting
    /// The connection is being repaired to complete creation.
    case createRepairing
    /// The connection is being repaired to complete deletion.
    case deleteRepairing
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .failed: return 2
      case .creating: return 3
      case .deleting: return 4
      case .createRepairing: return 5
      case .deleteRepairing: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .failed: return "FAILED"
      case .creating: return "CREATING"
      case .deleting: return "DELETING"
      case .createRepairing: return "CREATE_REPAIRING"
      case .deleteRepairing: return "DELETE_REPAIRING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "FAILED": self = .failed
      case "CREATING": self = .creating
      case "DELETING": self = .deleting
      case "CREATE_REPAIRING": self = .createRepairing
      case "DELETE_REPAIRING": self = .deleteRepairing
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .failed
      case 3: self = .creating
      case 4: self = .deleting
      case 5: self = .createRepairing
      case 6: self = .deleteRepairing
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .active: return try container.encode("ACTIVE")
      case .failed: return try container.encode("FAILED")
      case .creating: return try container.encode("CREATING")
      case .deleting: return try container.encode("DELETING")
      case .createRepairing: return try container.encode("CREATE_REPAIRING")
      case .deleteRepairing: return try container.encode("DELETE_REPAIRING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceConnectionPolicy"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
