// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Specifies eligibility information for the service.
public struct ServiceConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The eligibility criteria for the service.
  public var eligibilityCriteria: ServiceConfig.EligibilityCriteria =
    ServiceConfig.EligibilityCriteria()

  /// Output only. The end time for eligibility criteria support. If not
  /// specified, no planned end time is set.
  public var supportEndTime: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ServiceConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ServiceConfig().with { $0.eligibilityCriteria = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let eligibilityCriteria = CodingKeys(stringValue: "eligibilityCriteria")
    static let supportEndTime = CodingKeys(stringValue: "supportEndTime")

    static let _knownKeys: Set<Swift.String> = [
      "eligibilityCriteria",
      "supportEndTime",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      ServiceConfig.EligibilityCriteria.self, forKey: .eligibilityCriteria)
    {
      self.eligibilityCriteria = value
    }
    self.supportEndTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .supportEndTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.eligibilityCriteria, forKey: .eligibilityCriteria)
    try container.encodeIfPresent(self.supportEndTime, forKey: .supportEndTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The eligibility information for the service.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum EligibilityCriteria: Codable, Equatable, Hashable, Sendable {
    /// The service is not eligible for Data Transfer Essentials configuration.
    /// This is the default case.
    case unspecified
    /// The service is eligible for Data Transfer Essentials configuration only
    /// for Premium Tier.
    case networkServiceTierPremiumOnly
    /// The service is eligible for Data Transfer Essentials configuration only
    /// for Standard Tier.
    case networkServiceTierStandardOnly
    /// The service is eligible for Data Transfer Essentials configuration only
    /// for the regional endpoint.
    case requestEndpointRegionalEndpointOnly
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .networkServiceTierPremiumOnly: return 1
      case .networkServiceTierStandardOnly: return 2
      case .requestEndpointRegionalEndpointOnly: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ELIGIBILITY_CRITERIA_UNSPECIFIED"
      case .networkServiceTierPremiumOnly: return "NETWORK_SERVICE_TIER_PREMIUM_ONLY"
      case .networkServiceTierStandardOnly: return "NETWORK_SERVICE_TIER_STANDARD_ONLY"
      case .requestEndpointRegionalEndpointOnly: return "REQUEST_ENDPOINT_REGIONAL_ENDPOINT_ONLY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EligibilityCriteria/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ELIGIBILITY_CRITERIA_UNSPECIFIED": self = .unspecified
      case "NETWORK_SERVICE_TIER_PREMIUM_ONLY": self = .networkServiceTierPremiumOnly
      case "NETWORK_SERVICE_TIER_STANDARD_ONLY": self = .networkServiceTierStandardOnly
      case "REQUEST_ENDPOINT_REGIONAL_ENDPOINT_ONLY": self = .requestEndpointRegionalEndpointOnly
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EligibilityCriteria/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .networkServiceTierPremiumOnly
      case 2: self = .networkServiceTierStandardOnly
      case 3: self = .requestEndpointRegionalEndpointOnly
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("ELIGIBILITY_CRITERIA_UNSPECIFIED")
      case .networkServiceTierPremiumOnly:
        return try container.encode("NETWORK_SERVICE_TIER_PREMIUM_ONLY")
      case .networkServiceTierStandardOnly:
        return try container.encode("NETWORK_SERVICE_TIER_STANDARD_ONLY")
      case .requestEndpointRegionalEndpointOnly:
        return try container.encode("REQUEST_ENDPOINT_REGIONAL_ENDPOINT_ONLY")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `ServiceConfig`: `"type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceConfig"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceConfig"
  }

  /// Initialize an instance of `ServiceConfig` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceConfig"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ServiceConfig` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
