// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A Network Connectivity Center spoke represents one or more network
/// connectivity resources.
///
/// When you create a spoke, you associate it with a hub. You must also
/// identify a value for exactly one of the following fields:
///
/// * linked_vpn_tunnels
/// * linked_interconnect_attachments
/// * linked_router_appliance_instances
/// * linked_vpc_network
public struct Spoke: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Immutable. The name of the spoke. Spoke names must be unique. They use the
  /// following form:
  ///     `projects/{project_number}/locations/{region}/spokes/{spoke_id}`
  public var name: Swift.String = Swift.String()

  /// Output only. The time the spoke was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time the spoke was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional labels in key-value pair format. For more information about
  /// labels, see [Requirements for
  /// labels](https://cloud.google.com/resource-manager/docs/creating-managing-labels#requirements).
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. An optional description of the spoke.
  public var description: Swift.String = Swift.String()

  /// Immutable. The name of the hub that this spoke is attached to.
  public var hub: Swift.String = Swift.String()

  /// Optional. The name of the group that this spoke is associated with.
  public var group: Swift.String = Swift.String()

  /// Optional. VPN tunnels that are associated with the spoke.
  public var linkedVpnTunnels: LinkedVpnTunnels? = nil

  /// Optional. VLAN attachments that are associated with the spoke.
  public var linkedInterconnectAttachments: LinkedInterconnectAttachments? = nil

  /// Optional. Router appliance instances that are associated with the spoke.
  public var linkedRouterApplianceInstances: LinkedRouterApplianceInstances? = nil

  /// Optional. VPC network that is associated with the spoke.
  public var linkedVpcNetwork: LinkedVpcNetwork? = nil

  /// Optional. The linked producer VPC that is associated with the spoke.
  public var linkedProducerVpcNetwork: LinkedProducerVpcNetwork? = nil

  /// Output only. The Google-generated UUID for the spoke. This value is unique
  /// across all spoke resources. If a spoke is deleted and another with the same
  /// name is created, the new spoke is assigned a different `unique_id`.
  public var uniqueId: Swift.String = Swift.String()

  /// Output only. The current lifecycle state of this spoke.
  public var state: GoogleCloudNetworkConnectivityV1.State =
    GoogleCloudNetworkConnectivityV1.State()

  /// Output only. The reasons for current state of the spoke.
  public var reasons: [Spoke.StateReason] = []

  /// Output only. The type of resource associated with the spoke.
  public var spokeType: SpokeType = SpokeType()

  /// Optional. This checksum is computed by the server based on the value of
  /// other fields, and may be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Optional. The list of fields waiting for hub administration's approval.
  public var fieldPathsPendingUpdate: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Spoke`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Spoke().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let description = CodingKeys(stringValue: "description")
    static let hub = CodingKeys(stringValue: "hub")
    static let group = CodingKeys(stringValue: "group")
    static let linkedVpnTunnels = CodingKeys(stringValue: "linkedVpnTunnels")
    static let linkedInterconnectAttachments = CodingKeys(
      stringValue: "linkedInterconnectAttachments")
    static let linkedRouterApplianceInstances = CodingKeys(
      stringValue: "linkedRouterApplianceInstances")
    static let linkedVpcNetwork = CodingKeys(stringValue: "linkedVpcNetwork")
    static let linkedProducerVpcNetwork = CodingKeys(stringValue: "linkedProducerVpcNetwork")
    static let uniqueId = CodingKeys(stringValue: "uniqueId")
    static let state = CodingKeys(stringValue: "state")
    static let reasons = CodingKeys(stringValue: "reasons")
    static let spokeType = CodingKeys(stringValue: "spokeType")
    static let etag = CodingKeys(stringValue: "etag")
    static let fieldPathsPendingUpdate = CodingKeys(stringValue: "fieldPathsPendingUpdate")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "description",
      "hub",
      "group",
      "linkedVpnTunnels",
      "linkedInterconnectAttachments",
      "linkedRouterApplianceInstances",
      "linkedVpcNetwork",
      "linkedProducerVpcNetwork",
      "uniqueId",
      "state",
      "reasons",
      "spokeType",
      "etag",
      "fieldPathsPendingUpdate",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hub) {
      self.hub = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .group) {
      self.group = value
    }
    self.linkedVpnTunnels = try container.decodeIfPresent(
      LinkedVpnTunnels.self, forKey: .linkedVpnTunnels)
    self.linkedInterconnectAttachments = try container.decodeIfPresent(
      LinkedInterconnectAttachments.self, forKey: .linkedInterconnectAttachments)
    self.linkedRouterApplianceInstances = try container.decodeIfPresent(
      LinkedRouterApplianceInstances.self, forKey: .linkedRouterApplianceInstances)
    self.linkedVpcNetwork = try container.decodeIfPresent(
      LinkedVpcNetwork.self, forKey: .linkedVpcNetwork)
    self.linkedProducerVpcNetwork = try container.decodeIfPresent(
      LinkedProducerVpcNetwork.self, forKey: .linkedProducerVpcNetwork)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uniqueId) {
      self.uniqueId = value
    }
    if let value = try container.decodeIfPresent(
      GoogleCloudNetworkConnectivityV1.State.self, forKey: .state)
    {
      self.state = value
    }
    if let value = try container.decodeIfPresent([Spoke.StateReason].self, forKey: .reasons) {
      self.reasons = value
    }
    if let value = try container.decodeIfPresent(SpokeType.self, forKey: .spokeType) {
      self.spokeType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .fieldPathsPendingUpdate)
    {
      self.fieldPathsPendingUpdate = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.hub, forKey: .hub)
    try container.encode(self.group, forKey: .group)
    try container.encodeIfPresent(self.linkedVpnTunnels, forKey: .linkedVpnTunnels)
    try container.encodeIfPresent(
      self.linkedInterconnectAttachments, forKey: .linkedInterconnectAttachments)
    try container.encodeIfPresent(
      self.linkedRouterApplianceInstances, forKey: .linkedRouterApplianceInstances)
    try container.encodeIfPresent(self.linkedVpcNetwork, forKey: .linkedVpcNetwork)
    try container.encodeIfPresent(self.linkedProducerVpcNetwork, forKey: .linkedProducerVpcNetwork)
    try container.encode(self.uniqueId, forKey: .uniqueId)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.reasons, forKey: .reasons)
    try container.encode(self.spokeType, forKey: .spokeType)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.fieldPathsPendingUpdate, forKey: .fieldPathsPendingUpdate)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The reason a spoke is inactive.
  public struct StateReason: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The code associated with this reason.
    public var code: Spoke.StateReason.Code = Spoke.StateReason.Code()

    /// Human-readable details about this reason.
    public var message: Swift.String = Swift.String()

    /// Additional information provided by the user in the RejectSpoke call.
    public var userDetails: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `StateReason`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StateReason().with { $0.code = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let code = CodingKeys(stringValue: "code")
      static let message = CodingKeys(stringValue: "message")
      static let userDetails = CodingKeys(stringValue: "userDetails")

      static let _knownKeys: Set<Swift.String> = [
        "code",
        "message",
        "userDetails",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Spoke.StateReason.Code.self, forKey: .code) {
        self.code = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .message) {
        self.message = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .userDetails) {
        self.userDetails = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.code, forKey: .code)
      try container.encode(self.message, forKey: .message)
      try container.encode(self.userDetails, forKey: .userDetails)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The Code enum represents the various reasons a state can be `INACTIVE`.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum Code: Codable, Equatable, Hashable, Sendable {
      /// No information available.
      case unspecified
      /// The proposed spoke is pending review.
      case pendingReview
      /// The proposed spoke has been rejected by the hub administrator.
      case rejected
      /// The spoke has been deactivated internally.
      case paused
      /// Network Connectivity Center encountered errors while accepting
      /// the spoke.
      case failed
      /// The proposed spoke update is pending review.
      case updatePendingReview
      /// The proposed spoke update has been rejected by the hub administrator.
      case updateRejected
      /// Network Connectivity Center encountered errors while accepting
      /// the spoke update.
      case updateFailed
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .pendingReview: return 1
        case .rejected: return 2
        case .paused: return 3
        case .failed: return 4
        case .updatePendingReview: return 5
        case .updateRejected: return 6
        case .updateFailed: return 7
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "CODE_UNSPECIFIED"
        case .pendingReview: return "PENDING_REVIEW"
        case .rejected: return "REJECTED"
        case .paused: return "PAUSED"
        case .failed: return "FAILED"
        case .updatePendingReview: return "UPDATE_PENDING_REVIEW"
        case .updateRejected: return "UPDATE_REJECTED"
        case .updateFailed: return "UPDATE_FAILED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Code/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "CODE_UNSPECIFIED": self = .unspecified
        case "PENDING_REVIEW": self = .pendingReview
        case "REJECTED": self = .rejected
        case "PAUSED": self = .paused
        case "FAILED": self = .failed
        case "UPDATE_PENDING_REVIEW": self = .updatePendingReview
        case "UPDATE_REJECTED": self = .updateRejected
        case "UPDATE_FAILED": self = .updateFailed
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Code/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .pendingReview
        case 2: self = .rejected
        case 3: self = .paused
        case 4: self = .failed
        case 5: self = .updatePendingReview
        case 6: self = .updateRejected
        case 7: self = .updateFailed
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("CODE_UNSPECIFIED")
        case .pendingReview: return try container.encode("PENDING_REVIEW")
        case .rejected: return try container.encode("REJECTED")
        case .paused: return try container.encode("PAUSED")
        case .failed: return try container.encode("FAILED")
        case .updatePendingReview: return try container.encode("UPDATE_PENDING_REVIEW")
        case .updateRejected: return try container.encode("UPDATE_REJECTED")
        case .updateFailed: return try container.encode("UPDATE_FAILED")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.networkconnectivity.v1.Spoke.StateReason"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.Spoke"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
