// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The State enum represents the lifecycle stage of a Network Connectivity
/// Center resource.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum State: Codable, Equatable, Hashable, Sendable {
  /// No state information available
  case unspecified
  /// The resource's create operation is in progress.
  case creating
  /// The resource is active
  case active
  /// The resource's delete operation is in progress.
  case deleting
  /// The resource's update operation is in progress.
  case updating
  /// The resource is inactive.
  case inactive
  /// The resource's accept operation is in progress.
  case accepting
  /// The resource's reject operation is in progress.
  case rejecting
  /// The hub associated with this spoke resource has been deleted.
  /// This state applies to spoke resources only.
  case obsolete
  /// The resource is in an undefined state due to resource creation or deletion
  /// failure. You can try to delete the resource later or contact support for
  /// help.
  case failed
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .creating: return 1
    case .active: return 2
    case .deleting: return 3
    case .updating: return 6
    case .inactive: return 7
    case .accepting: return 8
    case .rejecting: return 9
    case .obsolete: return 10
    case .failed: return 11
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "STATE_UNSPECIFIED"
    case .creating: return "CREATING"
    case .active: return "ACTIVE"
    case .deleting: return "DELETING"
    case .updating: return "UPDATING"
    case .inactive: return "INACTIVE"
    case .accepting: return "ACCEPTING"
    case .rejecting: return "REJECTING"
    case .obsolete: return "OBSOLETE"
    case .failed: return "FAILED"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "STATE_UNSPECIFIED": self = .unspecified
    case "CREATING": self = .creating
    case "ACTIVE": self = .active
    case "DELETING": self = .deleting
    case "ACCEPTING": self = .accepting
    case "REJECTING": self = .rejecting
    case "UPDATING": self = .updating
    case "INACTIVE": self = .inactive
    case "OBSOLETE": self = .obsolete
    case "FAILED": self = .failed
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .creating
    case 2: self = .active
    case 3: self = .deleting
    case 6: self = .updating
    case 7: self = .inactive
    case 8: self = .accepting
    case 9: self = .rejecting
    case 10: self = .obsolete
    case 11: self = .failed
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("STATE_UNSPECIFIED")
    case .creating: return try container.encode("CREATING")
    case .active: return try container.encode("ACTIVE")
    case .deleting: return try container.encode("DELETING")
    case .updating: return try container.encode("UPDATING")
    case .inactive: return try container.encode("INACTIVE")
    case .accepting: return try container.encode("ACCEPTING")
    case .rejecting: return try container.encode("REJECTING")
    case .obsolete: return try container.encode("OBSOLETE")
    case .failed: return try container.encode("FAILED")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
